Components/Widgets/Content.js
Makes contentContainerStyle customizable in Content tag.
=> customizable contentContainerStyle in Content tag

Components/Widgets/Input.js
Add a reference object that we can expose at the Input object level
=> Add ref to TextInput

Components/Widgets/Icon.js
Theme was not applied to Icon component. iconFontFamily always defaulted to Ionicons
=> Theme is not applied to icon.

Components/Widgets/Content.js
Made `resetScrollToCoords` user definable.  Thoughts?
=> Kasv scroll fix

Components/Base/NativeBaseComponent.js, Components/Themes/dark.js, Components/Widgets/Picker.js, Components/Widgets/ProgressBar.ios.js, Components/Widgets/Switch.js, Components/Widgets/Title.js, Components/Widgets/View.js, Components/vendor/react-native-scrollable-tab-view/index.js
Remove trailing white spaces from certain files.
=> remove trailing white spaces.

Components/Widgets/Picker.ios.js
Remove getDefault in favour of getLabel accepting props to check the label for
Implement componentWillReceiveProps comparing current to the next label and setting state if necessary
#169
=> Picker dynamic values

.eslintrc.json, Components/Widgets/DeckSwiper.js, README.md, package.json
Config eslint to enforce a consistent coding style and best practices.
Once we get over the overwhelming number of indentation,  spaces, tabs, line endings and other annoying errors and warnings, We can start to reap the true benefits of eslint.  
Running "eslint --fix ."  would fix the large number of  errors and warnings but would create a large commit.
Trying to fix all errors and warnings will be tedious but I think is the best on the long run.
=> config eslint to enforce coding style (airbnb).

Components/Widgets/FooterTab.js
Very simple update to allow onPress on each tab item in footer tab
=> Add onPress support

Components/Widgets/Tabs.js
https://github.com/GeekyAnts/NativeBase/issues/181
=> fix: goToPage of Tabs

Components/Widgets/Badge.js
Allows to use styles like 'textDecorationLine'
=> Apply complete styling to the Badge text

Components/Widgets/Badge.js
A number of the propTypes definitions are malformed.
=> Fix BadgeNB propTypes definition.

Components/Widgets/CardItem.js
1. CardItem support for null or undefined children,
2. Airbnb rules.
=> #264 widgets do no support null or undefined children

Components/Widgets/Button.js
Referencing [#285](https://github.com/GeekyAnts/NativeBase/issues/285)
=> Change line 197 to fix toUpperCase error on Android

Components/Widgets/Picker.ios.js
#217
add style props:
```
itemTextColor,
iconColor,
modalStyle
```
=> add Picker style props 

Components/Widgets/CardItem.js, Components/Widgets/Gravatar.js, Components/Widgets/ListItem.js, index.js, package.json
Code mostly modified from Thumbnail component.
=> Gravatar component added

Components/Widgets/InputGroup.js, package.json
Fixes https://github.com/GeekyAnts/NativeBase/issues/252
The version bump is most likely unnecessary though.
=> remove Widgets/InputGroup type checking

.gitignore, Components/Themes/light.js, Components/vendor/react-native-scrollable-tab-view/DefaultTabBar.js
Also changing deviceWidth to a const, adding missing directories to .gitignore.
https://github.com/GeekyAnts/NativeBase/issues/433
=> Adding capability to set Tab Underline Color using the theme variables

ejectTheme.js
=> Update printed message to point to up to date docs

src/basic/ListItem.js
Hi, I am using NativeBase in my own personal project and came down to implement a requirement on my app two days ago where I found out long press event is not support by ListItem. Here is the change that add that capability to the ListItem. Cheers, Morteza
=> Adding long presss event support to ListItem

src/basic/List.js
Hope this will resolve the List DataSource issue
=> fixup! List implementation fix #601

src/basic/List.js
_scrollComponent is need to call the methods which are declared in ListView
=> get access to ListView

index.d.ts
In `index.d.ts`, `react-native` should be used for `ReactNative` specified properties.
=> Patch index.d.ts to working with typescript

package.json
Did this so we can use the `scrollToEnd()` function. It is really handy!!!
=> Updated react-native-keyboard-aware-scroll-view to latest version

src/basic/Tabs/ScrollableTabBar.js
=> use _.isEqual instead of JSON.stringify

src/basic/Picker.ios.js
headerBackButtonTextStyle prop option added for picker.
=> Picker modal Back Button Text Style

index.d.ts
Change cancelButtonIndex and destructiveButtonIndex to be optional
=> Typescript make ActionSheet parameters optional

index.d.ts
Input should has "disabled" props
=> fix Input interface type

index.d.ts
I just started using NativeBase, so I hope this is correct. Thanks!
=> Added missing last attribute to ListItem typings

src/theme/components/Header.js, src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Issue - Text not vertically centered in Header searchBar
=> Fix for issue #1028

src/basic/Tabs/index.js
Issue - Why does my `overlayTop` tab bar appear at bottom
=> Fix for issue #1330.

index.d.ts, src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
=> Removed unused variable listItemHeight

src/basic/Picker.ios.js
=> Added placeholderStyle to Picker.

src/theme/components/Card.js
Issue : card ui breaks on iphoneX
Possible fix for issue #612
=> Fix for issue #1234

src/basic/Button.js, src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Issue - Use theme to turn off uppercase buttons on Android
=> Added feature for issue #1235

src/basic/SwipeRow.js
Related to issue #1430 issuecomment-351650432
=> Added style implementation for SwipeRow.

src/basic/Picker.ios.js
Replaced ListView with FlatList in Picker
=> Possible Fix for issue #1239

index.d.ts, src/basic/CardItem.js
Added activeOpacity prop for CardItem.
=> Enhancement for issue #1453.

index.d.ts
=> Updated type definition for ActionSheet. Title optional.

index.d.ts
Associated with issue comment https://github.com/GeekyAnts/NativeBase/issues/1398#issuecomment-350639818
=> Added missing property style to interface separator in index.d.ts

index.d.ts
Added Btn, Tabs and Tabs missing types
=> Added Btn, Tabs and Tabs missing types

index.d.ts
Fix based on issuecomment
https://github.com/GeekyAnts/NativeBase/pull/1424#issuecomment-365357198
=> Changed 'SubTitle' to 'Subtitle' in index.d.ts

src/basic/Actionsheet.js
=> Changed Flatlist keytype from number to string

index.d.ts
This pull request adds the Type prop to Icon in the Typescript definition file.
=> Update TS Definition with Icon Type Prop

index.d.ts
Fix for issue #1629(Error in Typescript of SwipeRow definition)
=> Added missing props for SwipeRow in index.d.ts.

src/basic/Fab.js
Fix for issue #1618 (FAB children buttons don't use style from stylesheet)
=> Added stylesheet support for styling Fab child buttons.

README.md, src/basic/Tabs/index.js
Added content for supporting PR #1603
=> Added information about ignite native base boilerplate

src/basic/Input.js
Fix based on issuecomment https://github.com/GeekyAnts/NativeBase/issues/611#issuecomment-370208552
=> Fix for Input underline color (android)

index.d.ts, src/basic/IconNB.js
Fix for issuecomment https://github.com/GeekyAnts/NativeBase/issues/1468#issuecomment-369987482
=> Added evilIcons support for Icons

index.d.ts
=> Added the style property to the Checkbox definition in index.d.ts.

src/basic/Content.js, src/basic/Footer.js, src/basic/Header.js, src/theme/components/FooterTab.js, src/theme/components/Header.js, src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Reverts GeekyAnts/NativeBase#1614
=> Revert "Safearea implementation for Header, footer and Content"

src/basic/Fab.js
=> Fixed  FAB container flexDirection code

index.d.ts
Hi, I found textStyle is missing from Picker interface so I added it, thanks!
=> Add textStyle field to Picker property

src/theme/components/Button.js
Attempt to fix issue #1743 (small button with icon on iOS )
=> Added icon styles to small button theme.

src/theme/components/Header.js, src/theme/components/Item.js
Fix for issue-comment https://github.com/GeekyAnts/NativeBase/issues/1731#issuecomment-376349102
=> Changed searchbar input lineHeight in theme to null.

src/basic/Button.js
Fix for issue #1749 (Button not working nice on android with v2.4.1)
=> Added maxHeight to rounded button

src/basic/Content.js, src/theme/components/Content.js
Attempt to fix issue #1720 (Content with refreshControl and padder wrong paddings).
=> Moved padding from Content's style to contentContainerStyle.

index.d.ts
Fix for issue #1747 (keyboardShouldPersistTaps missing from typings)
=> Added contentProps to Tabs in index.d.ts

src/basic/Input.js
fixes: https://github.com/GeekyAnts/NativeBase/issues/1750
=> Use variables from theme if provided in Input component

index.d.ts
Fix for issue-comment : https://github.com/GeekyAnts/NativeBase/issues/1145#issuecomment-378173606
=> Overrided picker style type in index.d.ts to ReactNative.TextStyle

src/theme/components/Header.js
=> Attempt to reduce space between left button and title

src/theme/components/Card.js
Related issue #1819 (Remove box-shadow from card)
=> Added noShadow to card theme.

src/theme/components/CardItem.js
Fix for issue #1818 (Card border not displaying in Android)
=> Fixed - cardItem header's border is not getting displayed in android.

src/theme/components/Button.js
Fix for issue #1827 (button chinese and number , english vertical align)
=> Removed lineHeight dependency for text in button.

src/theme/components/CardItem.js
Fix for issue comment https://github.com/GeekyAnts/NativeBase/issues/1818#issuecomment-386188384
=> Fix - border not appearing for some bordered cardItem.

src/theme/components/ListItem.js
Fix for issue #1844 (How to remove bottom border of ListItem)
=> Fixed - noBorder with icon shows border.

src/basic/Picker.ios.js
Fix for issue #1843 (How can I style picker's iosIcon)
=> Added support to style iosIcon of picker.

src/theme/components/ListItem.js
=> Added noIndent props to listItem

index.d.ts
Fix for issue #1905(types: react-native types are wrong with 16.3+)
=> Updated with new types

index.d.ts
Fix for issue #1906(CheckBox components doesn't have testID prop available)
=> CheckBox interface extends Touchableopacity props.

src/theme/components/Segment.js
Fix for issue #1917(Segment overflow with three buttons only)
=> Removed horizontal button padding for segment button.

index.d.ts, src/basic/Picker.ios.js
Enhancement based on issue #1923(ModalStyle on Picker component for iOS)
=> Added back modalStyle for ios picker

src/basic/ListItem.js
=> ListItem to support all touchablenativefeedback props.

index.d.ts
The prop typing on button is missing "Icon" which is causing annoying TS errors.
=> Adding icon typing to button component

src/basic/Picker.ios.js
Enhancement based on issue #1825
=> Added prop enabled to picker for iOS

src/theme/components/Header.js
Support for issue #1981 (Header absolute/fixed value with transparent background)
=> Added transparent props to header.

index.d.ts
Fix for issue #1982  (Typo in onClose definition resulting in compilation error)
=> Fixed typo.

src/theme/components/Item.js
Fix for issue #1924(`<Input multiline>` doesn't work inside `<Item stackedLabel>`)
=> Removed fixed height and added minHeight for Item-stackedLabel

src/basic/Item.js
Fix for issue #1915(Icon problem when using Redux Form with NativeBase)
=> Added check to filter out Input.

src/basic/Header.js
Fix for #1985 (Header clipped on iPhoneX)
=> Attempt to fix header padding issue on iphoneX.

src/basic/Accordion.js, src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Added style support for accordion component.
=> Added border to accordion component.

index.d.ts, src/basic/Header.js, src/theme/components/Header.js
Added translucent props to header.
Support for issue-comment https://github.com/GeekyAnts/NativeBase/issues/1981#issuecomment-397921059 based on issue-comment https://github.com/GeekyAnts/NativeBase/issues/1981#issuecomment-398012027
=> Added Statusbar color support for transparent header on android.

src/basic/Item.js
Fix for issue #2000 and #2005 based on issuecomment https://github.com/GeekyAnts/NativeBase/issues/2005#issuecomment-398262593
=> Reverted fix 1606.

src/basic/DatePicker.js
Enhancement based on #2016 (DatePicker : onDateChange callback for Android)
=> Added onDateChange callback support for datePicker android.

src/theme/components/Card.js
=> Changed background color to transparent for Card props `transparent`.

src/theme/components/index.js
Fix for issue #2103 (transform (array of objects) not supported from theme files)
=> Support added for style property `transform`.

src/basic/Actionsheet.js
Enhancement based on issue #2090 (ActionSheet needs a way to hide on command)
=> Added hide function to actionsheet (android).

index.d.ts, src/basic/DatePicker.js
PR for Issue #2113 (Date Picker : set as disabled)
=> Added enabled props to datepicker

index.d.ts
reference: https://facebook.github.io/react-native/docs/picker.html#mode
=> types: added prop "mode" in Picker

index.d.ts, src/basic/ToastContainer.js
PR for issue #1287 based on PR #1304
=> Added hide function for hiding toast.

src/basic/Accordion.js
PR for issue #2116 ([Feature-Request] give Accordion a flexible dataArray)
=> Passing item as callback parameter instead of title and content.

src/theme/components/Card.js
=> Fixed - Card flexes with wrapping Content.

index.d.ts, package.json, src/basic/Drawer/index.js, src/index.js, src/vue-native.js
Reverts GeekyAnts/NativeBase#2100
=> Revert "Removed Drawer from NativeBase"

src/theme/components/index.js
I was searching my codebase for console log statements and found this in the native base code. It was probably used for debugging or something.
=> Removed commented console log statements

index.d.ts
Add tabs property to Typescript definition
=> Add tabs property to Typescript definition

src/basic/Content.js, src/basic/Footer.js, src/basic/Header.js
Fixes #2382. Similar to #2383, which was incorrectly closed. Now without committing dist files.
=> Allow iPhoneX feature flag to be modified from specified theme (instead of default)

src/basic/Header.js, src/basic/Picker.ios.js
Reverts GeekyAnts/NativeBase#2541
=> Revert "Pass through iosBarStyle from Picker to Header"

index.d.ts
This PR fixes #2662 .
I added Tabs `scrollWithoutAnimation` property in `index.d.ts`
=> [TS] Add `scrollWithoutAnimation` prop to Tabs

.gitignore, index.d.ts
Update the Toast.show() function in the index.d.ts file. Added the style field, as shown in this
issue in #840
Fixes #2679
=> Updated Toast.show in index.d.ts

index.d.ts
Added missing `color` and `standardStyle` types
=> TS: add missing Radio types

src/basic/Tabs/DefaultTabBar.js, src/basic/Tabs/ScrollableTabBar.js, src/basic/Tabs/index.js, src/theme/variables/platform.js
=> Adding TabBar disabled feature

src/basic/IconNB.js
=> feat: Add Icon FontAwesome5Pro support

src/theme/components/Icon.js
Actually I'm unable to customize Icon color component
=> Allow Icon to inherit color

package.json
Not needed creates annoying warning
=> Remove prettier

src/basic/Item.js, src/basic/Label.js
Feature: #2843 
PR to appreciation
=> Feature parameter floatBack

package.json
Upgrade `react-native-keyboard-aware-scroll-view` from `0.8.0` to `0.9.1`.
=> chore(): Update react-native-keyboard-aware-scroll-view dependency #2879

CONTRIBUTING.md, README.md
Added missing fullstops and colons
=> added missing fullstops and colons

src/basic/Tabs/index.js
bugfix of initialPage is not working on Android #2705
=> fix(): initialPage not working on Android #2705

README.md
[react-native-cli ](https://github.com/react-native-community/cli) package by default allow us auto link any packages.
@SupriyaKalghatgi  thanks. Please review this PR 🎉 that's my first PR 🙌
🙌Happy to contribute with your team🙌
=> docs |   RN : 0.60 supports auto-linking 

index.d.ts, src/basic/ListItem.js
- Added underlayColor props to ListItem
=> Added underlayColor props to ListItem

index.d.ts
[Added onScroll propTypes to Tabs  in TS](https://docs.nativebase.io/Components.html#tabs-def-headref)
=> Added onScroll propTypes to Tabs in TS

index.d.ts
Add missing type declaration for `first` and `last` properties of `CardItem`
=> fix(types): add first and last props for CardItem

src/basic/Item.js
=> fix(item): Foating label with initial value

src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Fixed issue #3064 
H3 Line height changed.
=> bug fix 3064

src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Button light transparent color fixed. 
`<Button light transparent > <Text>Light Button</Text></Button>`
=> bug fix 3071

index.d.ts, src/basic/Subtitle.js, src/theme/components/Subtitle.js, src/theme/components/Title.js
Also, `numberOfLines` of Subtitle should be 1.
=> Align text & subtitle's text to left on android

package.json, src/basic/Content.js
=> Fix #3179, #3183,  for broken react-native 0.63.0, upgrade dependencies

src/basic/ToastContainer.js
Fix non-working buttons in IOS after displaying the toast.
=> Toast bug fix

index.d.ts
The props for Textarea should be optional and not mandatory.
=> Made props for Textarea optional

src/basic/Fab.js
Added useNativeDriver:false to Animated.spring call in Fab
=> Added useNativeDriver:false to Animated.spring

index.d.ts, src/basic/Accordion.js
Document added in PR 
https://github.com/GeekyAnts/native-base-docs/pull/254
=> Accordion Header Index and Content Index - added

src/basic/SwipeRow.js
this._panResponder is undefined at rendering, it should be put it in the constructor.
=> this._panResponder undef fix

src/basic/Accordion.js
```
<Accordion dataArray={dataArray} expanded={[0, 2]} expandMultiple />
<Accordion dataArray={dataArray} expanded={0} expandMultiple />
<Accordion dataArray={dataArray} expanded={0} />
```
=> feat(accordion): accordion multiple items open added

src/basic/Item.js
#3072 
#3067 
#2937 
#2648 
Before:
After:
=> fix: floatingLabel with defaultValue workiing now

src/basic/Item.js
=> Fix: [ITEM] Floating label input with icon bug #2835

example/storybook/stories/hooks/usePopover/Usage.tsx, example/storybook/stories/hooks/usePopover/index.tsx, example/storybook/stories/index.ts, src/components/composites/Menu/Menu.tsx, src/components/composites/Popover/index.tsx, src/core/NativeBaseProvider.tsx, src/core/Popover/Context.ts, src/core/Popover/PopoverProvider.tsx, src/core/Popover/index.ts, src/core/Popover/props.ts, src/core/Popover/usePopover.ts, src/core/Popover/utils.ts, src/core/index.ts
=> ➕: Added usePopover

src/basic/DeckSwiper.js, src/basic/Fab.js, src/basic/ToastContainer.js
Seems like useNativeDriver was missed in a few places for #3136.
=> added missing useNativeDriver:false to DeckSwiper, Fab, and ToastContainer components.

src/components/composites/NumberInput/NumberInput.tsx, src/components/composites/NumberInput/props.tsx, src/components/composites/PinInput/index.tsx, src/components/composites/PinInput/props.tsx
=> fix: handling onChange manually

example/storybook/stories/examples/TodoApp.tsx, example/storybook/stories/examples/index.tsx, example/storybook/stories/index.ts
=> feat: added todo app example

src/basic/Accordion.js, src/theme/variables/commonColor.js, src/theme/variables/material.js, src/theme/variables/platform.js
Reverts GeekyAnts/NativeBase#3352
=> Revert "Revert "Feat/accordian disable row""

src/theme/components/input.ts
https://trello.com/c/y0HFEliV and https://trello.com/c/4K9WleDo
=> fix: increased border radius to md for input

src/theme/components/input.ts
=> fix: added red border for invalid input in all variant

src/components/composites/AppBar/AppBar.tsx
Card: https://trello.com/c/XtQXuYQM
=> fix: alignment fix

example/storybook/stories/components/primitives/Input/example.tsx, src/components/primitives/Input/IInputProps.ts, src/components/primitives/Input/index.tsx, src/theme/components/input.ts
=> fix: added hover style for web, floating label and redesign

example/storybook/stories/components/composites/PinInput/Usage.tsx, src/components/composites/PinInput/index.tsx, src/theme/components/pin-input.ts
- https://trello.com/c/2hpmkj0C
- https://trello.com/c/ga3jcXgE
=> fix: focus and design

src/components/composites/Accordion/Accordion.tsx, src/components/composites/Accordion/AccordionButton.tsx, src/components/composites/Accordion/AccordionIcon.tsx, src/components/composites/Accordion/AccordionItem.tsx, src/components/composites/Accordion/AccordionPanel.tsx, src/theme/components/accordion.ts, src/theme/components/index.ts, src/utils/getIndexedChildren.ts
- https://trello.com/c/iKqneIzg
- https://trello.com/c/wOnHQopS
=> fix: accordion redesign

example/storybook/stories/components/primitives/Switch/Sizes.tsx, example/storybook/stories/components/primitives/Switch/SwitchBgColor.tsx, src/components/primitives/Switch/index.tsx, src/components/primitives/Switch/types.ts, src/theme/components/switch.ts
=> fix: updated switch api and integrated theme

package.json, src/components/primitives/Button/index.tsx, src/components/primitives/Switch/index.tsx, yarn.lock
- Fixed dependencies
- Removed aria-describedby and aria-label from useButton. aria-describedby should only include ids of other elements (Still need to figure out an approach) and aria-label will be added using accessibilityLabel prop. (Handled in react-native-aria)
=> fix: v3 rn-aria dependencies

src/components/composites/KBD/index.tsx, src/theme/components/kbd.ts
=> fix: added _text

src/components/composites/Modal/index.tsx
This PR implements
1. Focus trapping on web modal
2. initial and final ref focus fix on the web
=> fix: modal focus - v3 modal focus behaviour on web

example/storybook/stories/components/composites/Breadcrumb/Basic.tsx, src/components/composites/Breadcrumb/Breadcrumb.tsx, src/components/composites/Breadcrumb/BreadcrumbItem.tsx, src/components/primitives/Link/index.tsx, src/components/primitives/Link/types.ts, src/components/primitives/Link/useLink.ts
This PR adds accessibility support for breadcrumbs.
Followed guide - https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html
=> v3 - Breadcrumbs accessibility

example/storybook/stories/components/composites/Breadcrumb/Composition.tsx, src/components/composites/Breadcrumb/BreadcrumbItem.tsx, src/components/composites/Breadcrumb/BreadcrumbSeparator.tsx, src/components/primitives/Link/index.tsx, src/components/primitives/Link/types.ts, src/components/primitives/Link/useLink.ts
The previous commit broke the custom onClick functionality  Link. This PR fixes it.
=> v3 fix: useLink onClick broken for web

src/components/primitives/TouchableItem/index.tsx
This PR fixes menu UI on android.
=> fix: menu item ui on android

src/components/composites/CircularProgress/CircularProgress.tsx, src/components/composites/CloseButton/index.tsx, src/components/composites/Divider/index.tsx, src/components/composites/Progress/index.tsx
- This PR adds accessibility announcements for progress indicators
=> fix: v3 progressbars accessibility announcement

src/components/composites/Alert/Alert.tsx, src/components/composites/Modal/Modal.tsx, src/core/Overlay/Wrapper.tsx, src/core/Overlay/types.ts
This PR adds alertdialog role to modal in case of AlertDialog
=> fix: v3 alertdialog role in modal

example/storybook/stories/components/composites/CircularProgress/Basic.tsx, example/storybook/stories/components/composites/CircularProgress/ColorScheme.tsx, example/storybook/stories/components/composites/CircularProgress/Colors.tsx, example/storybook/stories/components/composites/CircularProgress/Indeterminate.tsx, example/storybook/stories/components/composites/CircularProgress/Label.tsx, example/storybook/stories/components/composites/CircularProgress/MinMax.tsx, example/storybook/stories/components/composites/CircularProgress/Thickness.tsx, example/storybook/stories/components/composites/CircularProgress/TrackColor.tsx, example/storybook/stories/components/composites/CircularProgress/index.tsx, src/components/composites/CircularProgress/CircularProgress.tsx, src/components/composites/CircularProgress/types.ts, src/theme/components/circular-progress.ts
Also added colorScheme prop to make is consistent with Progress component.
=> Fix CircularProgress UI and add component level theme.

src/theme/components/slider.ts
Matched the style of slider with MD
=> fix: shadow of slider fixed

src/components/basic/FlatList/types.ts, src/components/basic/KeyboardAvoidingView/types.ts, src/components/basic/ScrollView/types.ts, src/components/basic/SectionList/types.ts, src/components/basic/StatusBar/types.ts, src/components/basic/View/types.ts, src/components/primitives/Button/Button.tsx, src/components/primitives/Button/types.ts, src/components/primitives/Spinner/index.tsx
Fixes:
- Typings for View, ScrollView, StatusBar, KeyboardAvoidingView, FlatList, SelectionList and Button
=> fix: typings

.github/ISSUE_TEMPLATE/bug_report.md, package.json
=> Update issue templates (#3772)

src/components/primitives/Select/types.ts
https://github.com/GeekyAnts/NativeBase/issues/3775
=> Fix: Add color prop typescript definition in Select

src/components/primitives/Box/index.tsx
https://github.com/GeekyAnts/NativeBase/issues/3774
=> Fix: Box With Linear gradient example produces warning. 

src/theme/components/heading.ts
Fixes https://github.com/GeekyAnts/NativeBase/issues/3781
=> fix: 3781 add font family 'heading' in heading theme

src/components/primitives/Input/InputBase.tsx, src/components/primitives/Text/index.tsx, src/hooks/useResolvedFontFamily.ts, src/theme/base/typography.ts, src/theme/components/input.ts
Fixes https://github.com/GeekyAnts/NativeBase/issues/3782
=> Fix/3782 Add tokenized fontFamily support in Input component 

src/components/primitives/Input/InputBase.tsx
This PR implements same fix for Input component as Text component 
Refer this PR to learn more.
https://github.com/GeekyAnts/NativeBase/pull/3821
=> Fix - custom font family in input

src/hooks/useResolvedFontFamily.ts
Fixes https://github.com/GeekyAnts/NativeBase/issues/3840
=> fix: bold italic on text

example/storybook/stories/components/composites/Fab/Basic.tsx, example/storybook/stories/components/composites/Fab/CustomPosition.tsx, example/storybook/stories/components/composites/Fab/Kitchensink-Basic.tsx, example/storybook/stories/components/composites/Fab/Kitchensink-CustomPosition.tsx, example/storybook/stories/components/composites/Fab/Kitchensink-Placement.tsx, example/storybook/stories/components/composites/Fab/Placement.tsx, package.json, src/components/primitives/Spinner/index.tsx
Adding Patch for Spinner component not visible on version 3.0.4.
=> Hotfix: 3.0.5 spinner visibility

CONTRIBUTING.md
We have changed our docs repo.
=> fix: updated docs link in contributing.md

src/components/primitives/Text/index.tsx
fixed support for numberOfLines props on Text
=> fix: fixed support for numberOfLines props

example/package.json, example/yarn.lock, src/components/composites/Backdrop/index.tsx
This PR fixes https://github.com/GeekyAnts/NativeBase/issues/3868
=> fix: backdrop cursor showing pointer on hover issue

.eslintrc.json, .vscode/settings.json, package.json, src/components/composites/Toast/ToastDummy.tsx, yarn.lock
Fix eslint issues
Chore - Fix eslint issues and enable eslint extension for vscode workspace
=> chore: eslint error on console.log, warning on unassigned let variable

src/components/primitives/Stack/Stack.tsx, src/theme/components/stack.ts, src/utils/getSpacedChildren.tsx
This PR fixes https://github.com/GeekyAnts/NativeBase/issues/3882
- Previously stack space's string props had hard coded values from theme
- Now picks from Stacks component theme.
=> fix: stack space extend issue

src/components/primitives/Box/index.tsx
To support fragments inside the box.
Box can support all type of children now.
Fix
=> fix: empty fragment support provided as a child

example/storybook/stories/components/primitives/Text/Basic.tsx, src/components/primitives/Text/index.tsx, src/hooks/useThemeProps/usePropsResolution.test.tsx, src/theme/base/typography.ts
- Letter spacing changes
Multiplied token value of letter spacing with font size and appended unit of font size.
- Line Height changes
Multiplied token value of line height with font size and appended unit of font size.
=> feat: letterspacing and lineheight changes

src/components/primitives/Stack/HStack.tsx, src/components/primitives/Stack/Stack.tsx, src/components/primitives/Stack/VStack.tsx
Added typings for direction in stack.
Added typings for direction in stack.
fix
=> fix: stack direction typings added

src/components/primitives/Checkbox/Checkbox.tsx, src/components/primitives/Checkbox/Checkbox.web.tsx, src/components/primitives/Checkbox/types.tsx, src/theme/components/checkbox.ts
You can now add any style on the basis of interaction.
Added pseudo props for interactivity styling.
fix
=> fix: added interaction styling props to checkbox

src/components/primitives/Input/InputAdvanced.tsx, src/components/primitives/Input/InputBase.tsx, src/components/primitives/Input/types.ts
Provided pseudo prop to style input at readonly condition and aliases to inputLeft and inputRight element.
Added _readOnly prop and alias to InputLeftElement and InputRightElement.
fix
=> fix: added readonly pseudo prop and alias to props

example/storybook/stories/index.ts, src/components/primitives/Select/Select.tsx, src/components/primitives/Select/SelectItem.tsx
- Able to select first option.
- Added _disabled for styles.
- solved not able to select first option issue.
- Added _disabled  pseudo prop for styling.
fix
=> fix: resolved a select bug and added disabled

src/components/basic/ScrollView/index.tsx, src/components/basic/index.tsx, src/index.tsx
=> fix: exported iscrollviewprops

example/storybook/stories/components/primitives/Hidden/hiddenFromAndToBreakpoints.tsx, src/hooks/useBreakpointValue.ts, src/hooks/useThemeProps/utils.ts, src/theme/tests/findLastValidBreakpoint.test.tsx, src/theme/tools/utils.ts
useBreakPointvalue hook now takes theme value
fix
=> fix: themes breakpoints issue solved

src/components/composites/Toast/Toast.tsx
Fixes - https://github.com/GeekyAnts/NativeBase/issues/3981
Pointer events none not working on toast.
[General] [Fixed] - Toast pointer events none
Tested existing examples and the example linked in the above issue
=> fix: toast with pointer events none

src/components/composites/Toast/Toast.tsx
Toast title and description were getting cutoff in ios devices.
This PR fixes #3973
=> fix: toast message cut off on ios

src/components/primitives/Icon/Icons/Chevron.tsx
Icon size in chevron icons was not increasing.
This PR fixes #3978
=> fix: chevron icons size fixed

src/components/primitives/Select/Select.tsx
On opening select, keyboard doesn't close.
This PR fixes #3975
=> fix: keyboard dismiss on select open on native devices

src/hooks/useBreakpointResolvedProps.ts, src/hooks/useThemeProps/utils.ts, src/theme/styled-system.ts
Fixed a issue in breakpoints hook
fix
=> fix: breakpoint fixes

example/storybook/stories/components/composites/Breadcrumb/Collapsible.tsx, example/storybook/stories/components/composites/Breadcrumb/Separators.tsx, src/components/composites/Breadcrumb/Breadcrumb.tsx, src/components/composites/Breadcrumb/types.ts, src/theme/components/breadcrumb.ts
Minor typing fixes 
Moved spacing to default theme
Fixed examples
=> fix: breadcrumb typings fix

src/components/primitives/Image/index.tsx
=> fix: image api

example/storybook/stories/components/primitives/Button/Composition.tsx, example/storybook/stories/components/primitives/Button/WithRef.tsx
Button storybook examples were breaking
fix
=> fix: button examples fixed

example/__snapshots__/storybook.test.js.snap, example/storybook/stories/components/primitives/Box/composition-card1.tsx, example/storybook/stories/components/primitives/Box/composition-card2.tsx, example/storybook/stories/components/primitives/Box/composition-card3.tsx, example/storybook/stories/components/primitives/ButtonGroup/sizes.tsx, src/theme/components/input.ts
Removed border radius pill from examples
fix
=> fix: border radius pill changed to 25

example/storybook/stories/components/composites/Progress/Basic.tsx, example/storybook/stories/components/composites/Progress/ColorScheme.tsx, example/storybook/stories/components/composites/Progress/Composition.tsx, example/storybook/stories/components/composites/Progress/CustomBgColor.tsx, example/storybook/stories/components/composites/Progress/Flat.tsx, example/storybook/stories/components/composites/Progress/Sizes.tsx, example/storybook/stories/components/primitives/Input/Masked.tsx, example/storybook/stories/components/primitives/Slider/Customized.tsx, example/storybook/stories/components/primitives/Slider/FormControlled.tsx, example/storybook/stories/components/primitives/Slider/Playground.tsx, example/storybook/stories/components/primitives/Slider/Size.tsx, example/storybook/stories/components/primitives/Slider/Value.tsx, example/storybook/stories/components/primitives/Slider/Vertical.tsx, example/storybook/stories/components/primitives/Slider/color.tsx, example/storybook/stories/components/primitives/Slider/isDisabled.tsx, example/storybook/stories/components/primitives/Slider/isReadOnly.tsx, example/storybook/stories/components/primitives/Slider/usage.tsx, example/storybook/stories/components/primitives/Spinner/color.tsx, example/storybook/stories/components/primitives/Spinner/usage.tsx, example/storybook/stories/components/primitives/Switch/Basic.tsx, example/storybook/stories/components/primitives/Switch/ColorSchemes.tsx, example/storybook/stories/components/primitives/Switch/Sizes.tsx, example/storybook/stories/components/primitives/Switch/SwitchBgColor.tsx, src/components/primitives/Slider/types.tsx, src/theme/components/slider.ts, src/theme/components/spinner.ts
switch, spinner, progress and password type input design
fix
=> fix: switch design changes

example/storybook/stories/components/basic/View/Basic.tsx
view example design changes
fix
=> fix: view example

example/storybook/stories/components/primitives/Heading/Basic.tsx, example/storybook/stories/components/primitives/Heading/Composition.tsx, example/storybook/stories/components/primitives/Heading/OverridenStyle.tsx, example/storybook/stories/components/primitives/Heading/Sizes.tsx
=> fix: heading design

example/storybook/stories/components/composites/Badge/color.tsx, example/storybook/stories/components/composites/Badge/composition.tsx, example/storybook/stories/components/composites/Badge/variants.tsx, example/storybook/stories/index.ts, src/theme/base/colors.ts, src/theme/components/badge.ts
=> fix: badge-design

src/hooks/useContrastText.ts, src/theme/components/button.ts
Removed excess code from button theme and added tertiary color.  
fix
=> fix: colors mapping fixed

src/components/primitives/Checkbox/Checkbox.tsx, src/components/primitives/Checkbox/CheckboxGroup.tsx, src/components/primitives/Radio/Radio.tsx, src/components/primitives/Switch/index.tsx, src/hooks/useThemeProps/usePropsResolution.tsx, src/theme/components/image.ts, src/theme/components/radio.ts, src/theme/components/switch.ts, src/theme/tools/utils.ts
Fixes for Radio, Checkbox, Image and Switch.
=> fix: image, checkbox, radio and switch

example/storybook/stories/components/composites/Container/index.tsx, example/storybook/stories/components/composites/Container/usage.tsx, example/storybook/stories/components/primitives/Flex/basic.tsx, example/storybook/stories/components/primitives/Flex/spacer.tsx, src/theme/components/divider.ts, src/theme/components/text.ts
Design changes for container and flex
=> fix: design dark mode

example/storybook/stories/components/basic/FlatList/Basic.tsx, example/storybook/stories/components/composites/Menu/Basic.tsx, example/storybook/stories/components/composites/Menu/Group.tsx, example/storybook/stories/components/composites/Menu/MenuOptionsGroup.tsx, src/theme/components/menu.ts
=> fix: menu designs

example/storybook/stories/components/basic/ScrollView/Basic.tsx, example/storybook/stories/components/basic/SectionList/Basic.tsx, example/storybook/stories/examples/TodoApp.tsx
=> fix: todo, scrollview, sectionlist design fix

src/hooks/useThemeProps/propsFlattener.tsx, src/hooks/useThemeProps/propsFlattenerTest.tsx, src/hooks/useThemeProps/usePropsResolution.tsx, src/hooks/useThemeProps/usePropsResolutionTest.tsx
Fix for Internal props merging between diffrent types of style.
=> Internal props merging

example/storybook/stories/hooks/useColorMode/Basic.tsx, example/storybook/stories/hooks/useColorModeValue/Basic.tsx, example/storybook/stories/hooks/useContrastText/Variations.tsx, example/storybook/stories/hooks/useMediaQuery/max-height.tsx, example/storybook/stories/hooks/useMediaQuery/min-width.tsx, example/storybook/stories/hooks/useMediaQuery/orientation.tsx, example/storybook/stories/theme/Custom/Content.tsx, example/storybook/stories/theme/Custom/CustomizingComponents.tsx, example/storybook/stories/theme/Custom/CustomizingTheme.tsx, example/storybook/stories/theme/Mode/Content.tsx
=> fix: design fixes

example/storybook/stories/components/composites/Toast/CloseToast.tsx, example/storybook/stories/components/composites/Toast/CustomComponent.tsx, example/storybook/stories/components/composites/Toast/CustomComponentWithCustomId.tsx, example/storybook/stories/components/composites/Toast/ToastVariants.tsx, src/components/composites/Toast/Toast.tsx
=> fix: toastdesign

src/hooks/useThemeProps/usePropsResolution.tsx, src/hooks/useThemeProps/usePropsResolutionTest.tsx
pseudo internal props merging conflict
=> fix: pseudo internal props merging conflict

example/storybook/stories/components/composites/Actionsheet/Composition.tsx, example/storybook/stories/components/composites/Actionsheet/CustomBackdrop.tsx, example/storybook/stories/components/composites/Actionsheet/DisableOverlay.tsx, example/storybook/stories/components/composites/Actionsheet/Icon.tsx, example/storybook/stories/components/composites/Actionsheet/Usage.tsx, example/storybook/stories/components/composites/AlertDialog/Basic.tsx, example/storybook/stories/components/composites/Avatar/size.tsx, src/components/composites/Actionsheet/ActionsheetContent.tsx, src/theme/components/actionsheet.ts
=> fix: actionsheet design

example/storybook/stories/components/composites/Actionsheet/Icon.tsx, src/theme/components/input.ts
removed specificity props in input theme
=> fix: specificity props removed

example/storybook/stories/components/primitives/Hidden/hiddenOnColorModes.tsx
=> fix: example

example/storybook/stories/components/basic/ScrollView/Basic.tsx, example/storybook/stories/components/primitives/Checkbox/controlledCheckbox.tsx, example/storybook/stories/components/primitives/Checkbox/disabled.tsx, example/storybook/stories/components/primitives/Checkbox/invalid.tsx, example/storybook/stories/components/primitives/Checkbox/size.tsx, example/storybook/stories/components/primitives/Checkbox/uncontrolledCheckbox.tsx, example/storybook/stories/components/primitives/Checkbox/withRef.tsx, example/storybook/stories/components/primitives/Icon/ThirdPartyIcons.tsx, example/storybook/stories/components/primitives/Icon/index.tsx, example/storybook/stories/components/primitives/Input/Basic.tsx, example/storybook/stories/components/primitives/Input/Controlled.tsx, example/storybook/stories/components/primitives/Input/Elements.tsx, example/storybook/stories/components/primitives/Input/FormControlled.tsx, example/storybook/stories/components/primitives/Input/Masked.tsx, example/storybook/stories/components/primitives/Input/Size.tsx, example/storybook/stories/components/primitives/Input/Variant.tsx, example/storybook/stories/components/primitives/Link/CompositeLink.tsx, src/theme/components/menu.ts
=> fix: docs-fixes

src/theme/styled-system.ts
Mapping of background to backgroundColor
=> support for background prop

src/hooks/useThemeProps/utils.ts
=> fix: icons shadow

src/components/composites/Transitions/Slide.tsx
Fixes - https://github.com/GeekyAnts/NativeBase/issues/4104
[Fix] [General] - Actionsheet overlay dismiss
=> fix: actionsheet overlay not working

src/components/primitives/Select/Select.tsx
Fixes https://github.com/GeekyAnts/NativeBase/issues/4126 and https://github.com/GeekyAnts/NativeBase/issues/4122
=> fix: height prop not working in select

src/components/primitives/Text/index.tsx
added responsive support for noOfLines and numberOfLines
=> fix: added responsive support for noOfLines and numberOfLines

example/__snapshots__/storybook.test.js.snap, package.json
The PR is aimed at making the DX better. It includes removing the snapshot test on every commit.
Two things have changed in this particular PR:
* Snapshot test will happen on manual command, i.e. `commit-test`. Earlier it used to run on pre-commit hook.
* A snapshot is added for the section `Third-party icons` in `Icon` component.
=> fix: removed snapshot test and added snapshot icon example

src/components/primitives/Spinner/types.tsx
=> fix: fixed typings for spinner

src/components/primitives/Input/InputAdvanced.tsx, src/theme/tools/utils.ts
Attempts to fix - https://github.com/GeekyAnts/NativeBase/issues/4234
=> fix: pass shadow and opacity in box in input advance

src/components/composites/Avatar/Group.tsx, src/components/composites/FormControl/FormControlErrorMessage.tsx
Fixed rendering issues when no child is provided.
=> fix: rendering issue when no child

src/components/composites/AspectRatio/index.tsx, src/components/primitives/Select/Select.tsx, src/components/primitives/Select/types.ts, src/theme/tools/utils.ts
This PR fixes the issue where custom breakpoints don't work as expected.
=> Fix Custom Breakpoints not working as expected

src/components/composites/AspectRatio/index.tsx, src/components/primitives/Select/Select.tsx, src/components/primitives/Select/types.ts
This PR fixes docs prop table not visible issue.
=> Fix AspectRatio for getting used in Prop table on Docs

package.json
Changes to enable Tree shaking.
=> fix: optimise bundle for tree shaking

src/components/composites/Drawer/index.tsx, src/components/composites/Modal/index.tsx, src/components/composites/index.ts, src/components/primitives/index.ts, src/index.tsx
Exporting a few unexported types
=> fix: exporting unexported types

src/components/primitives/Input/Input.tsx, src/components/primitives/Input/InputAdvanced.tsx, src/theme/components/input.ts
Fixes: https://github.com/GeekyAnts/NativeBase/issues/4266
=> fix: input overflow issues fixed

example/storybook/stories/components/primitives/Radio/formControlled.tsx, src/components/primitives/Radio/Radio.tsx, src/components/primitives/Radio/Radio.web.tsx
Fixes: https://github.com/GeekyAnts/NativeBase/issues/4151
=> fix: formcontrol disabled on radiogroup fixed

src/components/primitives/Checkbox/Checkbox.tsx, src/components/primitives/Checkbox/SizedIcon.tsx
Fixed failing test cases that were happening because of the checkbox.
=> fix: checkbox test cases fixes

src/components/primitives/Select/Select.tsx, src/theme/components/input.ts, src/theme/components/select.ts
Update Select to optimize Select's performance #4176.
=> feat: update select to fix performance issues

src/components/basic/FlatList/FlatList.tsx, src/components/basic/FlatList/index.tsx, src/components/basic/FlatList/types.ts
added _contentContainerStyle for flatList [#4168]
=> feat: added _contentContainerStyle for flatList

src/components/primitives/Input/InputAdvanced.tsx, src/theme/base/shadows.ts, src/theme/components/input.ts
=> fix: added none shadow and fixed shadow in advance

src/hooks/useMediaQuery.ts
=> fix: fixed the useMediaQuery hook

src/components/primitives/Pressable/Pressable.tsx, src/components/primitives/Pressable/types.ts
Fix for `_disabled` props [#4351]
=> fix: fixed _disable prop

src/components/composites/Toast/Toast.tsx, src/core/hybrid-overlay/HybridProvider.tsx
Stopped re-rendering of components inside the provider
https://medium.com/@ryanflorence/react-context-and-re-renders-react-take-the-wheel-cd1d20663647
Render multiple boxes and then change props for one of them.
=> feat: provider optimisation fixed

src/index.tsx
=> fix: removed default export

package.json, src/core/color-mode/hooks.tsx
Fixed the re-rendering caused due to useColorMode hook
=> fix: function wrapped under usecallback hook

src/components/primitives/Spinner/index.tsx
[#4416] Fix the crashes happening on style props.
=> fix: style props resolution

example/storybook/stories/components/primitives/Input/Controlled.tsx
=> fix: controlled input example

src/hooks/useThemeProps/propsFlattener.tsx, src/hooks/useThemeProps/usePropsResolution.tsx, src/theme/components/input.ts, src/utils/styled.tsx
fix: input background not applying
=> fix: input background not applying

src/components/composites/Toast/Toast.tsx
I have added memoization on toast (built in useToast)
I am using toast in useEffect
The following code provokes an infinite useEffect calls
```
const [state, setState] = useState();
const toast = useToast();
const toastRef = useRef();
useEffect(()=> {
...
setState(newState);
...
...
toastRef.current = toast.show(...);
}, [toast]);
```
[PERF] [TOAST] - memoize toast
No change in user interface
=> fix: memoize toast

src/components/composites/IconButton/index.tsx, src/components/primitives/Button/Button.tsx
fix: buttons reacting on _focusVisible prop
=> fix: buttons reacting on _focusVisible prop

example/storybook/stories/components/primitives/Input/Elements.tsx
Added type=password to the Password input element
=> added variable to show/hide password

src/components/composites/Modal/Context.ts, src/components/composites/Modal/Modal.tsx, src/components/composites/Modal/ModalContent.tsx
In Modal component, added `visible` prop to the contextValue.
In ModalContent component, changed useEffect logic by adding `visible` prop as dependancy.
=> fix: modal inital ref issue fixed

src/components/primitives/Button/types.ts
Add types for _disabled, _hover, _focus, _pressed, _loading and _spinner for button
=> fix: add _disable, _loading, _hover, _pressed, _focus, _spinner

example/storybook/stories/components/basic/FlatList/Basic.tsx, src/components/basic/FlatList/FlatList.tsx, src/components/basic/FlatList/types.ts, src/components/primitives/Select/Select.tsx
github Issue:- [https://github.com/GeekyAnts/NativeBase/issues/4469](url)
NativeBase FlatList was not properly typed when it's compared with react-native FlatList.
=> Fix: flatlist prop type

src/components/primitives/Switch/index.tsx
isDisabled and isInvalid as prop in FormControl was not working for switch
=> fix: isDisabled, isInvalid props for form control

src/components/composites/Skeleton/SkeletonText.tsx
Fixed key prop warning in SkeletonText component #4473 
=> fix: add key prop

src/theme/base/colors.ts
for this issue: https://github.com/GeekyAnts/NativeBase/issues/4494
=> fix: derived colors without type

src/theme/base/colors.ts
Reverts GeekyAnts/NativeBase#4493
=> Revert "fix: derived colors without type"

src/hooks/useThemeProps/propsFlattener.tsx
fix: added new specificity in precedence and init state
=> fix: added new specificity in precedence and init state

example/storybook/stories/components/composites/Popover/Basic.tsx, example/storybook/stories/components/composites/Popover/PopoverPositions.tsx
fix: height prop is taking 60% of mobile screen devices
=> fix: removed height prop from Popover examples

src/utils/getAbsoluteChildren.ts, src/utils/getAttachedChildren.ts, src/utils/getIndexedChildren.ts, src/utils/getSpacedChildren.tsx
When use NativeBase with Next.js 12, in development console it shows some warns about anonymous arrow function :
```
warn  - ./node_modules/native-base/lib/module/index.js
Anonymous arrow functions cause Fast Refresh to not preserve local component state.
```
fix: warnings in Next.JS about anonymous arrow functions
Develop a Next.js project with NativeBase
=> fix: anonymous arrow functions

src/theme/base/colors.ts
Reverts GeekyAnts/NativeBase#4505
=> Revert "Revert "fix: derived colors without type""

src/components/primitives/Image/index.tsx
Image component was not updating the source when changed using hook.
=> fix: image hook update

src/theme/components/input.ts
Made few minor changes in input base style.
=> feat: input theme changes

src/theme/components/heading.ts
=> feat: heading POC changes

src/components/primitives/Input/Input.tsx
fixed `_hover` and `_disabled` pseudo props
=> fix: props for input base

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/auto_assign.yml, .github/stale.yml
Adding config for the stale bot.
=> Adding bot config

example/storybook/stories/examples/TodoApp.tsx
=> fix: todo example

example/storybook/stories/components/composites/factory/ref.tsx
=> fix: color of input in factory example

example/storybook/stories/components/primitives/Input/Elements.tsx
Note: the above PR is made to resolve the issue in kitchenSink
=> fix: added password visibility in inputs element example

src/components/primitives/Select/Select.tsx
=> fix: select undefined error for empty list

src/components/composites/Transitions/Slide.tsx, src/components/primitives/Checkbox/SizedIcon.tsx
- require cycle warning for slide and sizeIcon component.
=> fix: cycle warning fixes in slide/size icon

src/components/basic/SectionList/SectionList.tsx, src/components/basic/SectionList/types.ts
- SectionList was not properly typed.
- fixed using assertion same as flatList.
=> fix: sectionlist type issue

example/storybook/stories/components/composites/Menu/Group.tsx, example/storybook/stories/components/composites/Popover/PopoverPositions.tsx, example/storybook/stories/components/composites/Transitions/Slide.tsx
Fixed issues mentioned in the [jira card](https://geekyants.atlassian.net/browse/NTVBS-926)
=> fix: updated storybook

example/storybook/stories/components/composites/Badge/color.tsx, example/storybook/stories/components/composites/FormControl/CustomStyle.tsx
=> fix: replacing KeyboardAwareScrollView

src/hooks/useThemeProps/usePropsResolution.test.tsx
=> added test cases for pseudo props

src/components/composites/AspectRatio/index.tsx
=> Fix AspectRatio

src/components/composites/Progress/index.tsx
=> fix: progress api

src/components/composites/Container/index.tsx, src/theme/components/container.ts
=> feat: decoupled theme for container

src/components/composites/Skeleton/Skeleton.tsx, src/components/composites/Skeleton/SkeletonText.tsx, src/components/composites/Skeleton/types.tsx, src/theme/components/skeleton.ts
- Added `_stack` to internal stack for `SkeletonText`
- Added `overflow` to theme for `Skeleton`.
=> feat: decoupling of skeleton

src/theme/base/colors.ts
=> feat: text color palette

example/storybook/stories/components/composites/IconButton/Sizes.tsx, example/storybook/stories/components/primitives/Button/sizes.tsx, src/components/primitives/Button/Button.tsx, src/components/primitives/Button/types.ts, src/theme/components/button.ts, src/theme/components/divider.ts, src/theme/components/icon-button.ts, src/theme/components/icon.ts
- new _icon internal pseudo prop for Button
- Button design changes
- Divider design changes
=> feat: _icon internal prop and design changes for button and divider

src/components/primitives/Button/Button.tsx, src/theme/components/button.ts
Added option to show/hide `isLoadingText`
=> fix: isloadingtext not showing option

src/theme/components/button.ts, src/theme/styled-system.ts
=> fix: added a new prop to disable text selection

src/theme/components/slider.ts
- Slider thumb pointer issue with the web.
=> fix: slider thumb pointer

src/theme/components/icon-button.ts
- `subtle` variant design changes
-  fix icon color for `unstyled` variant
=> fix: iconbutton design fixes

src/theme/components/progress.ts
- Added `border-radius` to filled track.
=> fix: filled track border radius

src/theme/components/slider.ts
- added `opacity` for the `disabled` state.
=> fix: slider disabled state opacity issue

src/theme/base/colors.ts
=> fix: color change

example/storybook/stories/components/composites/Toast/ToastPositions.tsx, example/storybook/stories/components/composites/Toast/VariantRecipies.tsx
=> fix: toast example

src/theme/components/slider.ts
=> fix: disabled opacity

src/theme/components/button.ts, src/theme/styled-system.ts
=> fix: button disabled

src/theme/components/actionsheet.ts
=> fix: theme fixes

example/storybook/stories/components/composites/FormControl/Usage.tsx
=> fix: formcontrol example

example/storybook/stories/components/composites/Alert/action.tsx, example/storybook/stories/components/composites/Alert/basic.tsx, example/storybook/stories/components/composites/Alert/colorScheme.tsx, example/storybook/stories/components/composites/Alert/composition.tsx, example/storybook/stories/components/composites/Alert/status.tsx, example/storybook/stories/components/composites/Alert/usage.tsx
=> fix: alert close icon focus

src/components/primitives/Input/Input.tsx, src/components/primitives/Stack/Stack.tsx, src/theme/components/icon-button.ts, src/theme/components/input.ts
fix: the border issue is shifting the layout on focus of input box
=> fix: input shift on focus

src/theme/components/actionsheet.ts
- Fix `bg color` for `ActionsheetContent`
=> fix: actionsheet content bg

src/theme/components/input.ts
fix: Input is overflowing from its wrapper
=> fix: set width of Input according to wrapper

src/components/primitives/Button/Button.tsx
=> fix: fab icon

example/storybook/stories/components/composites/Actionsheet/Icon.tsx, example/storybook/stories/components/composites/Actionsheet/Usage.tsx, src/components/composites/Actionsheet/ActionsheetItem.tsx, src/components/composites/Actionsheet/types.tsx, src/theme/components/actionsheet.ts
=> Actionsheet.Item API and UI updates

src/components/composites/Fab/Fab.tsx
=> fix: fab variant

example/storybook/stories/components/composites/Alert/action.tsx, example/storybook/stories/components/composites/Alert/basic.tsx, example/storybook/stories/components/composites/Alert/colorScheme.tsx, example/storybook/stories/components/composites/Alert/composition.tsx, example/storybook/stories/components/composites/Alert/status.tsx, example/storybook/stories/components/composites/Alert/usage.tsx
=> fix: changed close icon color

example/storybook/stories/components/primitives/Input/Basic.tsx, example/storybook/stories/components/primitives/Input/Controlled.tsx, example/storybook/stories/components/primitives/Input/Masked.tsx, example/storybook/stories/components/primitives/Input/Size.tsx, example/storybook/stories/components/primitives/Input/Variant.tsx
- Input example fix - Input width was weird for android / IOS.
=> fix: input width

example/storybook/stories/components/composites/Divider/Basic.tsx, example/storybook/stories/components/composites/Divider/Orientation.tsx
- _light - muted.800
- _dark - muted.50
=> fix: change divider bg

README.md
=> fix: changed slack badge to discord badge

src/theme/components/slider.ts
=> hotfix: slider color

example/storybook/stories/components/primitives/Input/Size.tsx, example/storybook/stories/components/primitives/Input/Variant.tsx
=> fix: input example center

src/theme/components/menu.ts
- fix menu item focus border issue
=> fix: menuitem focus

src/components/primitives/Overlay/Overlay.tsx
=> fix: menu android freezing issue

src/theme/components/button.ts
- fix button padding for `sm` , `md` and `lg`.
=> fix: button size

example/storybook/stories/components/primitives/Select/Basic.tsx, src/components/primitives/Select/Select.tsx
=> fix: select click issue in ios and web

src/theme/tools/utils.ts
=> fix: input rounded prop

src/theme/components/popover.ts
=> fix: popover close in android

package.json, src/components/primitives/Checkbox/Checkbox.tsx, yarn.lock
Reverts GeekyAnts/NativeBase#4984
=> Revert "Fix/checkbox group rerendering issue"

example/tests/storybook.test.js.snap.android, example/tests/storybook.test.js.snap.ios, example/tests/storybook.test.js.snap.node, example/tests/storybook.test.js.snap.web, src/theme/components/icon.ts
Reverts GeekyAnts/NativeBase#4983
=> Revert "Feat/snapshot updates"

package.json, src/components/primitives/Checkbox/Checkbox.tsx, yarn.lock
Reverts GeekyAnts/NativeBase#4987
=> Revert "Revert "Fix/checkbox group rerendering issue""

example/tests/storybook.test.js.snap.android, example/tests/storybook.test.js.snap.ios, example/tests/storybook.test.js.snap.node, example/tests/storybook.test.js.snap.web, src/theme/components/icon.ts
Reverts GeekyAnts/NativeBase#4988
=> Revert "Revert "Feat/snapshot updates""

example/storybook/stories/components/composites/Toast/VariantRecipies.tsx
- Changed condition for status
=> fix: change status condition

src/components/primitives/Button/types.ts
=> fix: pseudo prop typing for button

example/storybook/stories/components/primitives/Pressable/Events.tsx, example/tests/storybook.test.js.snap.android, example/tests/storybook.test.js.snap.ios, example/tests/storybook.test.js.snap.node, example/tests/storybook.test.js.snap.web
=> fix: pressable example and update snapshots

src/components/composites/IconButton/index.tsx
=> fix: icon button props

src/factory/component.tsx
=> fix: factory fn memo for makestyle component

src/components/composites/Fab/Fab.tsx
- Extracted button related props from `Fab`.
=> fix: button specific prop fix fab

src/utils/useKeyboardBottomInset.ts
=> fix: usekeyboard-bottom-inset

src/theme/styled-system.ts
- fix: revert font transformer
=> fix: revert transformer of font

src/components/composites/Transitions/Fade.tsx, src/components/composites/Transitions/ScaleFade.tsx, src/components/composites/Transitions/types.tsx
- fix: animation api fade scale-fade #5084
=> fix: animation api fade scale-fade

src/components/composites/Toast/Toast.tsx
- fix: toast keyboard avoiding view using bottom inset #5052
=> fix: toast keyboardavoiding view using bottom inset

src/theme/components/toast.ts
- fix: adding position fixed in web for toast #4975
=> fix: adding position fixed in web for toast

example/storybook/stories/components/composites/Toast/StatusRecipies.tsx
Fix status condition for status recipies example
=> fix: status condition

src/utils/getSpacedChildren.tsx
- fix: type fix for flatternchild
=> fix: type fix for flatternchild

CONTRIBUTING.md
=> fix: docs link

src/index.tsx, src/theme/index.ts
=> fix: styledprop export

README.md
=> Fix/update readme 3.4.9

src/components/primitives/Button/ButtonGroup.tsx
ButtonGroup was breaking for `false` , `null` and `string` values of children.
=> fix: falsy child break

src/theme/components/heading.ts
=> fix: heading sizes

src/core/color-mode/hooks.tsx
fix: flickering issue of `colormode` ios #4930
=> fix: flickering issue of colormode ios

example/storybook/stories/components/primitives/Input/Elements.tsx
=> fix: element example

src/theme/components/button.ts
- Removing `mode` function in `button.ts` theme file and replacing it with `_light` & `_dark`.
=> fix: removing mode and adding _light and _dark

src/core/color-mode/hooks.tsx
=> fix: remove event listner

package.json, src/theme/base/colors.ts
Reverts GeekyAnts/NativeBase#5317
=> Revert "Fix/add theme color palette"

src/theme/components/alert.ts, src/theme/components/avatar.ts, src/theme/components/badge.ts, src/theme/components/divider.ts, src/theme/components/form-control.ts, src/theme/components/icon-button.ts, src/theme/components/menu.ts, src/theme/components/popover.ts, src/theme/components/progress.ts, src/theme/components/slider.ts, src/theme/components/tooltip.ts
=> fix: remove light pseudo props from base style

src/theme/components/actionsheet.ts, src/theme/components/alert-dialog.ts, src/theme/components/alert.ts, src/theme/components/avatar.ts, src/theme/components/badge.ts, src/theme/components/button.ts, src/theme/components/checkbox.ts, src/theme/components/divider.ts, src/theme/components/form-control.ts, src/theme/components/heading.ts, src/theme/components/icon-button.ts, src/theme/components/icon.ts, src/theme/components/input.ts, src/theme/components/inputleftaddon.ts, src/theme/components/inputrightaddon.ts, src/theme/components/menu.ts, src/theme/components/modal.ts, src/theme/components/popover.ts, src/theme/components/pressable.ts, src/theme/components/progress.ts, src/theme/components/radio.ts, src/theme/components/select.ts, src/theme/components/skeleton.ts, src/theme/components/slider.ts, src/theme/components/switch.ts, src/theme/components/text.ts, src/theme/components/tooltip.ts
- Removing `_light` from theme files making it default.
=> Fix: removing light from theme

src/components/composites/Avatar/Group.tsx
=> fix: key prop warning

package.json, yarn.lock
- added dependency of use-subscription
=> fix: dependancy issue of use-subscription

src/components/composites/Alert/types.tsx
**Old Content -** 
The colorScheme of the Alert.
**New Content -** 
The color scheme of the Alert.
=> fix: content changes in alert types

example/storybook/stories/components/primitives/Flex/basic.tsx, example/storybook/stories/hooks/useContrastText/Basic.tsx, example/storybook/stories/theme/Custom/CustomizingVariant.tsx, src/components/composites/AlertDialog/types.ts, src/components/composites/Modal/types.ts, src/components/composites/Toast/types.ts
=> Docs example fixes

example/storybook/stories/components/primitives/Flex/basic.tsx, example/storybook/stories/components/primitives/Icon/CreateIcon.tsx, example/storybook/stories/hooks/useContrastText/Basic.tsx, example/storybook/stories/theme/Custom/CustomizingVariant.tsx, package.json, src/components/composites/AlertDialog/types.ts, src/components/composites/Modal/types.ts, src/components/composites/Toast/types.ts, src/core/color-mode/hooks.tsx
=> Canary patch

example/storybook/stories/components/primitives/Select/FormControlled.tsx, example/storybook/stories/components/primitives/Select/SelectLongList.tsx
Fix: alignment issue in select component
=> fix: alignment issue in select component

src/components/composites/Modal/types.ts
=> Fix Type description in Modal

src/utils/useResponsiveQuery/useResponsiveQuery.web.tsx
- fix: multiple responsive prop fix.
=> fix: responsive nextjs

.github/workflows/build.yml
=> Back merge master

package.json, src/components/primitives/Checkbox/CheckboxGroup.tsx, yarn.lock
fix for defect - [CheckBox.Group bugs #5073](https://github.com/GeekyAnts/NativeBase/issues/5073)
=> fix: CheckBox.Group bugs #5073

package.json
=> Back merge Canary patch

package.json, yarn.lock
=> Hotfix: Checkbox group

README.md
=> Update README.md - Evolution to gluestack
