- Components/Base/NativeBaseComponent.js
- Components/Widgets/Badge.js
- Components/Widgets/Button.js
- Components/Widgets/Card.js
- Components/Widgets/CardItem.js
- Components/Widgets/CheckBox.js
- Components/Widgets/Container.js
- Components/Widgets/Content.js
- Components/Widgets/Footer.js
- Components/Widgets/H1.js
- Components/Widgets/H2.js
- Components/Widgets/H3.js
- Components/Widgets/Header.js
- Components/Widgets/Icon.js
- Components/Widgets/Input.js
- Components/Widgets/InputGroup.js
- Components/Widgets/List.js
- Components/Widgets/ListItem.js
- Components/Widgets/Picker.js
- Components/Widgets/Switch.js
- Components/Widgets/Text.js
- Components/Widgets/Thumbnail.js
- Components/Widgets/Title.js
- Components/Widgets/View.js
- Utils/computeProps.js
in order to remove deprecation warnings introduced with react-native [0.25.1](https://github.com/facebook/react-native/releases/tag/v0.25.1)
Todo:
> Import react from react

- Utils/computeProps.js
When I tried to add a `refreshControl` prop to `<Content>` to enable pull-to-refresh feature, a `Maximum call stack size exceeded` error was thrown and app crashed.
```
<Content refreshControl={
<RefreshControl
refreshing={this.props.isFetching}
onRefresh={() => this.props.dispatch(fetchData())}
/>
}>
```
Actually, I found that passing a prop with a component as value to any components from NativeBase, such as `<Card myCustomProp={<Text>hello</Text>} />`, results in the same error.
The problem is, in the `computeProps()` function which is called by every NativeBase widget in `NativeBaseComponent` class, styled default props and incoming props are recursively merged with `_.merge()`. When the incoming props contain a React component, the merge is too deep to finish and crash occurs. 
My …
> Fix error when adding props with components to NativeBase widgets

- Components/Widgets/InputGroup.js
Currently, the following snippet: 
```js
...
<InputGroup>
{null}
<Input />
</InputGroup>
...
```
Results in this error:
```sh
InputGroup.getIconProps
InputGroup.js:105
InputGroup.renderChildren
InputGroup.js:171
InputGroup.render
InputGroup.js:236
<unknown>
ReactCompositeComponent.js:793
measureLifeCyclePerf
ReactCompositeComponent.js:74
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
ReactCompositeComponent.js:792
ReactCompositeComponentWrapper._renderValidatedComponent
ReactCompositeComponent.js:819
ReactCompositeComponentWrapper.performInitialMount
ReactCompositeComponent.js:361
ReactCompositeComponentWrapper.mountComponent
ReactCompositeComponent.js:257
Object.mountComponent
ReactReconciler.js:47
```
This update allows for inserting a null value inside …
> Allow null block inside InputGroup Component

- Components/Widgets/Tabs.js
I was encountering a problem, where if a null value was passed as a child to Component, it threw a few errors.
This .filter() removes all falsey values from this.props.children, preventing the errors, and returning the correct result.
> Add .filter() call on this.props.children

- Components/Widgets/Tabs.js
If only one child is given, this.props.children is not an array of objects, just a single object, breaking both .filter() in this file, and .map() in the ScrollableTabView component.
This checks if this.props.children is an array, and creates a single item array if it's not, thus allowing .filter() and .map() calls.
> Ensure that <Tabs /> props.children is an array

- Components/Widgets/Header.js
**Issue:**
When using the `iconRight` attribute on `Header` with a single button, a negative margin is applied to pull it flush with the edge of the screen, but it is incorrectly placed on the left side. (This is more obvious with an opaque button, but even with a transparent button seen here, it leaves a large gap between the icon and right side of the screen.
**Fix:**
The negative margin is moved to the right side so the button is flush.
_Note that you can compare this fix with the other layout conditions in the same file, where identical properties are applied. It appears to have simply been copied incorrectly when the "single-button/iconRight" logic was added._
> Fix: Single right-aligned header button margin

- Components/Widgets/FooterTab.js
The FooterTab component modifies the children's props in place using _.remove, which causes the children array to be broken on subsequent renderings. This fix simply shallow clones the children props before making changes to it, fixing this issue #256 . Sorry if this isn't exactly right, but it should be the right direction at least. Let me know if there's any issues with it :)
> Fix modification of props #256

- Components/Widgets/InputGroup.js
Hi, @sankhadeeproy007 
When I use a Button inside a InputGroup without Icon, an error occurs:
```
<InputGroup>
<Input placeholder="PASSWORD" secureTextEntry/>
<Button>
<Icon name="ios-eye-off"/>
</Button>
</InputGroup>
```
I modify the InputGroup to make it work.
> Fix button display error

- Components/Widgets/Spinner.js
This enables the spinner container to be squared, like in this screenshot: https://www.dropbox.com/s/oo7osg9lpfjhcbx/Screenshot%202016-11-23%2020.02.43.png?dl=0
> Add default width to Spinner

- Components/Widgets/InputGroup.js
- Components/Widgets/Picker.ios.js
- Components/Widgets/Picker.js
Present implementation does not work well with a Picker inside a form. The styling does not match with the styling of other form elements containing Input. This PR also resolves issues [Issue 1](https://github.com/GeekyAnts/NativeBase/issues/295) and [Issue 2](https://github.com/GeekyAnts/NativeBase/issues/89)
> Support use of Picker inside an InputGroup in a form

- index.d.ts
> Add missing properties in index.d.ts

- package.json
**Changes**
- Fixed empty readme page on npmjs.com (see image below)
Tested by publishing to [another package name](https://www.npmjs.com/package/native-base-transpiled)
**Before fix**
**After fix**
> Fix readme not showing up on npmjs.com

- package.json
The new version of `react-native-vector-icons` uses `react-native@0.40.0`
that has breaking change in headers.
> Update vector icons to 4.0.0

- .babelrc
- Components/Widgets/Header.js
- __tests__/Components/Widgets/Header.android.js
- __tests__/Components/Widgets/Header.ios.js
- __tests__/Components/Widgets/__snapshots__/Header.android.js.snap
- __tests__/Components/Widgets/__snapshots__/Header.ios.js.snap
- package.json
I had a bug when using the Header in the following way:
```
const someVar = false;
let someButton = null;
if (someVar === true) {
someButton = <Button><Icon name='ios-arrow-back' /></Button>;
}
return (
<Header>
{someButton}
<Title>Test</Title>
</Header>
);
```
Issue is that the Component Header checks if the children is an array or not. If not it will just immediately return the children to be rendered. Otherwise it will try to layout the children accordingly to what is being passed. 
Before I started fixing the issue I however was not very comfortable with changing anything due to the code quality and no tests being around. 
Therefore I first added tests for the use cases I found in the documentation, using [Jest](https://facebook.github.io/jest/). This has been done in …
> Fix Header when a `null` child is being passed

- .babelrc
- .eslintignore
- .gitignore
- .npmignore
- package.json
**Changes**
- Add `npm run compile` command to transpile source into `dist` directory
- `npm publish` publishes the `dist` directory, the `Fonts` directory, and `index.d.ts`
- Ignore extraneous files on publish (images, config files, dotfiles)
Fixes the following issues: #396, #400
**Testing**
- Published as [native-base-transpiled](https://www.npmjs.com/package/native-base-transpiled) and used locally on a React Native project
- Verify via [unpkg](https://unpkg.com/native-base-transpiled@0.5.25/) that correct files are published
> Add transpilation step to ensure native-base works with Jest out of the box

- src/basic/H1.js
- src/basic/H2.js
- src/basic/H3.js
H1, H2, H3 should not check children types. The Text component is already handling type checking for child nodes. This will allow us to use `Text` inside `H1/H2/H3` tags.
> H1/H2/H3 should not check children types.

- ejectTheme.js
Hi @sankhadeeproy007 
https://github.com/GeekyAnts/NativeBase/commit/93565b5ca3b9d2049a8cd8223561de6abd7272bc didn't quite do the job, because it advises the consumer to import ./native-base-theme/index which doesn't exist and resulted in an error:
ResolveError: Unable to resolve module ./native-base-theme/index
> Resolves https://github.com/GeekyAnts/NativeBase/issues/511

- src/basic/Picker.ios.js
The stock Picker didn't allow me to sufficiently customize the button that gets rendered in the form.  This PR lets you customize the rendering of it with a property called renderButton.
Ex:
`
renderButton(onPress) {
return <Button onPress={onPress}>....
}
render() {
return <Picker renderButton={this.renderButton} ...
}
`
I'd like to see this pattern more and more in NativeBase.  I've found the components are flexible enough most of the time, but when you really need to customize, they lack the appropriate hooks.  The good news it's easy to do.
> Complete customization of Picker button

- index.d.ts
The Left,Right,Body definitions seem to be missing in the index.d.ts.
> Add Left,Right,Body typescript definitions

- index.d.ts
- src/basic/Button.js
- src/basic/Text.js
This is a followup to my last PR which wasn't merged quite right. The TypeScript definitions I included weren't merged and the treatment of the new `uppercase` prop was a bit inconsistent.
This removes the old `capitalize` prop from `Button` that must have accidentally been included when the component was updated to 2.x. It has no functionality and isn't documented, so I removed it.
This properly names the new prop on `Text` to _uppercase_ [in accordance with the equivalent CSS text-transform property](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#Syntax) along the the necessary TypeScript definitions (and a couple other missing ones I need).
> Remove old 'capitalize' prop from Button, use 'uppercase' on Text instead

- src/basic/Button.js
- src/smart/STabs/index.js
fix #264
Child can be `null` or `false` and `child.type` will throw error.
example:
```js
isLoading = false // or true
return <Button>
{isLoading && <Spinner/>}
{!isLoading && <Text>Send</Text>}
</Button>
```
> check children in Children.map

- src/basic/DeckSwiper.js
This is quite useful if someone wants to know the selected item when swiping the cards.
> Pass the selected item to onSwipeLeft/onSwipeRight callbacks

- src/basic/ListItem.js
If I am not mistaken, you currently have to supply both `onPress` *and* `onLongPress` to `ListItem` in order to enable android ripples. In my app I would like to enable them, but only by using `onPress` as I have no use for `onLongPress`.
With this change either prop will enable ripples.
> Enable androidRipple with either onPress or onLongPress

- src/basic/DeckSwiper.js
`this.props.looping || true` will always set the looping state to true (Not only undefined but also false)
Set `this.state.looping` to true only if `this.props.looping` is undefined
> Make looping property to work as intended

- src/basic/Button.js
Current: If `props.activeOpacity` will be `0`, `activeOpacity` is being `0.5`
Fix for above issue.
> zero value check added for button's active opacity.

- index.d.ts
This PR adds two props which were missing from index.d.ts: `androidStatusBarColor` (on `Header`) and `color` (on `CheckBox`). It also points the `header` prop on `Tab` to the right type (previously it was referencing the property type definition, and not the actual component class. Since the names clash, I used an underscored alias.
> Add missing props in TypeScript definitions file

- src/basic/Tabs/ScrollableTabBar.js
This was causing the tabs to not be measured, and breaking the indicator layout on scrollable tabs.
> Set layout handler on button when tab has no name

- src/theme/variables/commonColor.js
- src/theme/variables/material.js
- src/theme/variables/platform.js
The style variable "listBg" is used in src/theme/components/ListItem.js:402, but was not defined.
> Bugfix missing list bg

- README.md
Fixed a small typo in readme. `KitchenSink` was missing an `e`
> Fixed minor typo in readme

- src/basic/ListItem.js
Currently `androidRipple` and `androidRippleColorDark` variables for `ListItem` come from `platform` theme.
> Enable Android ripple effect settings from custom theme

- src/basic/Fab.js
Ref.: https://github.com/GeekyAnts/NativeBase/issues/1214
This PR cancels the `setTimeout` timers on `Fab` that might attempt to change the component state after it's unmounted.
> Cancel Fab timers on unmount

- src/basic/Actionsheet.js
When i click the backbutton or overlay in android actionsheet, modal closing but not have any callback event.
> Android Actionsheet BackButton and Overlay Click Event.

- src/Utils/mapPropsToStyleNames.js
- src/basic/Tabs/Button.android.js
- src/basic/Tabs/Button.ios.js
- src/basic/Tabs/Button.windows.js
- src/basic/Tabs/SceneComponent.js
- src/basic/Tabs/StaticContainer.js
- src/basic/Tabs/index.js
When using Webpack/Rollup with ES6 modules, mixed module formats can cause errors.
This fixes that.
Also, I am a bit confused by the file `src/Utils/mapPropsToStyleNames.js`. It appears the authors intended it to be something like a default parameter? But assigning to `mapPropsToStyleNames` without a declaration is an error.
> Fix mixed ES6 imports with CommonJS exports.

- src/basic/Tabs/DefaultTabBar.js
- src/basic/Tabs/ScrollableTabBar.js
The variable `mapPropsToStyleNames` is undefined when it's later used. I assume the intention is to use the definition in `Utils`.
> DefaultTabBar and ScrollableTabBar use mapPropsToStyleNames without import

- src/basic/Actionsheet.js
Fixed Issue 1353 - Actionsheet of android returns buttonIndex as string instead of number
> Fix for #1353.

- src/basic/Icon/NBIcons.json
Issue - Icon "happy" maps to non-existent "md-happy-outline" on android
> Fix for issue #1331.

- index.d.ts
Issue - SwipeRow not exported in TypeScript definition
Added missing export SubTitle in typescript declaration file
> Fix for issue #1423

- src/basic/Tabs/index.js
<Tabs /> underline is not properly positioned when there is a lot of stuff to render.
This fix eliminates issue in my case, but simply putting around hundred <Text /> children breaks it 100% on iOS.
Further investigation required
> Tabs initial setup change

- src/basic/Item.js
`input` was not defined anything, so the code would break. I realised that the var is not used at all, so I removed it.
> removes unused and broken var declaration

- package.json
This change guarantees the use of the npm repository in the stable versions of the repositories: react-native-drawer@2.5.0 and react-native-keyboard-aware-scroll-view@0.4.2.
> Fix for issue #1521

- index.d.ts
Fix for issue #1565 (Typescript Types for List missing)
> Added leftOpenValue property to interface List

- .eslintrc.json
- src/basic/Actionsheet.js
Resolves #1595. This will make sure that a large modal created for android action sheet stays inside the bounds of the root container.
Before:
After:
Extra change:  Eslint was unable to read the rc file as it was written. I updated to insure this change would be within the parameters of the eslint guidelines for the project.
> Max height on actionsheet modal

- README.md
As the nodei.co downloads badge doesn't work, I added the shields.io npm downloads badge instead.
> [README] Fix Npm downloads badge

- src/basic/Icon/index.js
This prevents icon names from being mapped via `NBIcons.json` when prop `type` is configured as something other than `"Ionicons"`.
Without this fix the following name is incorrectly mapped to `"md-send"` which fails to load for type `"MaterialIcons"`:
``` javascript
<Icon name="send" type="MaterialIcons" />
```
> Consider Icon type prop when fetching names

- src/theme/components/Button.js
Attempt to fix issue #1742(Disabled transparent buttons should stay transparent and "disable" text inside)
> Added support for disabled transparent buttons in theme.

- index.d.ts
Fix for issue #1803 (focus, _root, getRef - missing from typings)
> Added getRef to Input interface in index.d.ts.

- src/basic/Actionsheet.js
Fix for issue #1938 (Excess space on Android ActionSheet)
> Removed title space from actionsheet when there is no title prop.

- dist/src/basic/Root.js
- src/basic/Root.js
This PR is related to issues #1397, #1315, #937.
There is potential that React Native may unmount and remount the root node of the application due to Android lifecycle events without clearing the JS execution environment.  (This is possible even if native-base's `Root` is the top level component.)  This results in `actionSheetInstance` being invalid as it pointed to the previously mounted application root's ActionSheet component that was unmounted.  
This pull request updates the static `actionSheetInstance` and `toastInstance` refs regardless of what state they are in such that stale refs will be overwritten appropriately.
According to the [React Ref documentation](https://reactjs.org/docs/refs-and-the-dom.html):
> React will call the ref callback with the DOM element when the component …
> If application root is reinitialized, update ActionSheet and Toast refs

- src/basic/Icon/index.js
Add missing property `type` to Icon.PropTypes
> Add type to proptypes

- src/basic/Picker.ios.js
Attempt to fix #983 (Picker : undefined is not an object :child.props.value)
> Supports different Picker.Item generation.

- index.d.ts
refs #2126
disabled property on DatePicker Props have wrong syntax definition and is causing the error I mention in #2126 also formatChosenDate was added to DatePicker but the definition was not added in the DatePicker Props definition I added it.
> Fix date picker props

- src/basic/Gravatar.js
The import `prop-types` package line was missed when migrating from `React.PropTypes` to `prop-types` package in the Gravatar component.
> missing import `prop-types` package

- src/basic/Drawer/index.js
This should fix the dark drawer issue on android.
Please see [#2312](https://github.com/GeekyAnts/NativeBase/issues/2312)
> fix android drawer overlay

- src/theme/components/index.js
cardTheme currently doesn't get the theme variables passed to it and therefore doesn't get themes styles.
> pass variables param to cardTheme

- src/basic/Header.js
- src/basic/Picker.ios.js
Previously there was no way to set the barStyle on iOS when using the Picker component.
Also adds <StatusBar hidden={false} /> for react-native v0.58.
> Pass through iosBarStyle from Picker to Header

- README.md
CRNA has been retired in favor of expo-cli - https://facebook.github.io/react-native/docs/getting-started.html
> Clarify installation instructions and change CRNA to Expo

- index.d.ts
TypeScript detects an error when add onScroll property to Content Component.
It seems Contents should extend `KeyboardAwareScrollViewProps`.
Similar to #1908,
actually It should add KeyboardAwareScrollViewProps instead of ScrollViewProperties.
> TS: Add KeyboardAwareScrollViewProps to Content interface

- README.md
The latest version of Expo requires `expo-font` to be installed separately and awaited before the container loads like the [kitchen sink app](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/CRNA/src/boot/setup.js) does.
Related https://github.com/GeekyAnts/native-base-docs/pull/203
> Updated Getting Started for newer version of Expo

- index.d.ts
After exploring how to change the outer circle color of radio button in native base i have found that in Radio.js file 
this.props.color is defined but not defined in Interface of Radio Button in the file i.e index.d.ts
So it should be defined so that intelligence should work
> color prop defined in Radio Interface

- index.d.ts
Bordered and underline were missing from the type definition of Textarea.
> Add missing Textarea type definitions

- package-lock.json
- package.json
Address lodash vulnerability found in lodash versions before 4.17.12
https://npmjs.com/advisories/1065
Fixes #2773 
- I think there are a few changes in package-lock.json because I ran the install with npm version `6.9.2`. Let me know if they break compatibility and I can roll them back
- This really should just be a one-line change (+- a few lines in package-lock.json)
> Upgrade lodash to ^4.17.14

- index.d.ts
Content interface in /index.d.ts extends KeyboardAwareScrollViewProps but defines some properties as Object and String, instead of the types from KeyboardAwareScrollViewProps
> remove Content interface conflicts with KeyboardAwareScrollViewProps

- index.d.ts
The scrollWithoutAnimation property of [Tabs](https://docs.nativebase.io/Components.html#tabs-def-headref) component has default property.
(See: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Tabs/index.js#L56)
But, TS2741 error occur when not give it.
```
error TS2741: Property 'scrollWithoutAnimation' is missing in type '{ children: any[]; renderTabBar: () => Element; }' but required in type 'Readonly<Tabs>'.
146       <Tabs
~~~~
node_modules/native-base/index.d.ts:786:4
786                 scrollWithoutAnimation: boolean;
~~~~~~~~~~~~~~~~~~~~~~
'scrollWithoutAnimation' is declared here.
```
This is due to incorrect type definition file.
> scrollWithoutAnimation should be optional

- package.json
- yarn.lock
I've got a lot of security warning emails from projects using NativeBase.
Summary:
1. Bump dependency versions to patched version.
2. `npm run lint` and `npm run traspile` pass.
> fix security issues / vulnerabilities reported by npm audit

- src/basic/ToastContainer.js
This fixes the issue of `Toast` hiding behind the `keyboard` in `ios`. #2844 was reported for `android` but it was working fine in `android`.
> Fix #2844 - IOS

- src/basic/Tabs/DefaultTabBar.js
I have seen some crash reports about backgroundColor: null in my tools, specially with 32bit android devices.
> replace bgColor `null` with `transparent`

- index.d.ts
Hi! I found this typo at index.d.ts where `NativeBase.Thumbnail` definition had a "variuos" instead of "various"
It's actually my first pull request into an OSS software, so I hope i did it right (i only changed the typo at my own branch).
Keep up with the nice work, and I hope to contribute more in the future! :D
> Fixed typo at NativeBase.Thumbnail definition

- index.d.ts
- src/basic/Actionsheet.js
This change allows configuring the icon type when using an ActionSheet with icons. Right now you can only use icons from the default IonIcons family.
> Allow specifying icon type in icon ActionSheet

- src/basic/Picker.ios.js
This PR propagates testID to Picker.ios.js, specifically to the `FlatList` component as there is a custom implementation for Picker on iOS. Currently it is not being propagated.
> Add testID to Picker.ios

- src/theme/components/Item.js
There will be no fixed width issue for `<Input/>` in `<Item>` for android.
> bug fix 2634

- src/basic/IconNB.js
Fontisto icons has been linked. 
`import { Icon } from 'native-base'`
`<Icon type="Fontisto" name="aws" />`
> bug fix 3063

- src/basic/ListItem.js
The issue this PR addresses is here: https://github.com/GeekyAnts/NativeBase/issues/3028
Currently on the latest version of native-base 2.13.8, `ListItem` component does not show visual feedback of press on Android. It does, however, show visual feedback of press on iOS and web. To clarify, the press is being registered as can be seen by checking `onPress`. It is just the visual feedback not showing anything.
This is fixed by adding the prop `useForeground` for ListItem since it uses react-native's `TouchableNativeFeedback` for android only.
Since ListItem works straight out of the box for iOS and web as intended, it should also do the same for android without having to add that prop every time before using it.
The snack reproducible is in the issue linked above but will link here again. …
> Make ListItem Show Visual Feedback by Default for Android

- index.d.ts
When using NativeBase in any typescript project with the setting "noImplicitAny" enabled, the typescript checker fails with error:
`node_modules/native-base/index.d.ts:308:23 - error TS7006: Parameter 'item' implicitly has an 'any' type.`
* Create a new typescript project with the setting `noImplicitAny` set to `true`.
* Add NativeBase package.
* Use any NativeBase component in a view.
* Run the type checker.
Explicitly adding the any type for the item parameter removes the error.
---
Fixes #2971
> Removes implicit any issue.

- index.d.ts
I messed up the commit message of my last PR, so I opened this one.
The documentation says "`Icon` can take any two of the following attributes: name, ios, android."
But when using `ios` and `android`, it will trigger the error `Property 'name' is missing`.
Or maybe it's better to be defined like this to meet what the documentation says?
```typescript
interface IconBase extends Testable {
name?: string;
type?: "AntDesign" | "Entypo" | "EvilIcons" | "Feather" | "FontAwesome" | "FontAwesome5" | "Foundation" | "Ionicons" | "MaterialCommunityIcons" | "MaterialIcons" | "Octicons" | "SimpleLineIcons" | "Zocial";
// TODO position attribute of ReactNative.FlexStyle hasn't another position values without "absolute" and "relative"
style?: any;
onPress?: (e?: any) => any;
active?: boolean;
ios?: …
```
> fix(types): make name of Icon optional

- src/basic/Picker.ios.js
`Picker` will also check `SafeAreaView` now because I have added `content` for `Flatlist` on device rotation.
> bug fix 2990

- src/theme/components/Button.js
Hi, Issue: #2962, Buttons fixed.
> bug fix 2962

- src/theme/components/Header.js
Issue #3002 Fixed in Android. 
`<Header>`
`<Left style={{flex: 1}}><Button transparent ><Text>Cancel</Text></Button></Left>`
`<Body><Text>Header</Text></Body>`
`<Right style={{flex: 1}}><Button transparent ><Text>Cancel</Text></Button></Right>`
`</Header>`
Before
After
> bug fix 3002

- src/basic/Button.js
Hi, `buttonUppercaseAndroidText={false}` will work from now on in `Button`.
> bug fix 2904

- src/theme/components/Header.js
#3095 fixed. 
paddingTop has been removed from Header for iOS.
Before
After
> bug fix 3095

- src/basic/Text.js
This happens since they are sending invalid properties with this.props
```
Warning: Received `true` for a non-boolean attribute `uppercase`.
If you want to write it to the DOM, pass a string instead: uppercase="true" or uppercase={value.toString()}.
```
> fix(): warning uppercase a text component

- src/basic/Picker.ios.js
For Android, we are using picker from 'react-native' for picker but for iOS, we are using FlatList. 
**So we need to provide key for selected item in picker for iOS**. 
#3134
> bug fix 3134

- index.d.ts
Add missing type declaration `floatBack`  property for `Label`, used by [Item](https://github.com/GeekyAnts/NativeBase/blob/5c190746544293aa9c434c4831771f7e17043317/src/basic/Item.js#L423)
> fix(types): add  floatBack for Label

- package.json
- src/basic/Picker.android.js
- src/basic/Picker.ios.js
- src/basic/Picker.js
- src/basic/PickerItem.js
imported picker from @react-native-community/picker
> fix: error->importing picker from react-native core is deprecated

- src/basic/Fab.js
Fixes web crash due to TouchableNativeFeedback.Ripple being undefined on web.
Fixes #3227
> Fab: don't use TouchableNativeFeedback.Ripple if not Android

- src/basic/Tabs/DefaultTabBar.js
This PR contains the fix for the issue in `Tab` due to which passing them `disabled={true}` or `disabled={false}` keeps them disabled.
For reference: 
https://github.com/GeekyAnts/NativeBase/issues/2833
> Fix disabled true/false have the same effect on Tab (issue#2833)

- src/basic/ToastContainer.js
Added useNativeDriver to animated.timing call in ToastContainer
> Fixing warning -> Animated: useNativeDriver was not specified.

- src/basic/IconNB.js
`Fontisto` was not included in the propTypes of the `IconNB`
> fix: missing value Fontisto added to IconNB's prop types

- src/basic/Actionsheet.js
#1231 
`style` and `fontStyle` added in `ActionSheet` for Android.
```
<Button
onPress={() =>
ActionSheet.show(
{
options: BUTTONS,
cancelButtonIndex: CANCEL_INDEX,
destructiveButtonIndex: DESTRUCTIVE_INDEX,
title: 'Testing ActionSheet',
style: {backgroundColor: 'yellow'},
fontStyle: {color: 'red'},
},
(buttonIndex) => {
this.setState({clicked: BUTTONS[buttonIndex]});
},
)
}>
<Text>Actionsheet</Text>
</Button>
```
> feat: style and fontStyle added in ActionSheet

- src/theme/variables/commonColor.js
- src/theme/variables/platform.js
#3201, #3197 
checkBox: Before
checkBox: After
> fix: checkbox fontsize and iconSize changed

- src/basic/Tabs/index.js
fix for "TypeError: this.requestAnimationFrame is not a function" bug when using Tabs
> Fix requestAnimationFrame bug in Tabs

- index.d.ts
Vector Icons supports `solid` and `light` props.
It works well, but does not exists on typescript definition. So I added it.
https://github.com/oblador/react-native-vector-icons#multi-style-fonts
> Add FontAwesome5 style props on type definition

- package.json
When the keyboard is open console is throwing out an error `currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput`
Native Base is using 1.0.0 version for `@codler/react-native-keyboard-aware-scroll-view` To resolve this issue it needs to update to the 1.0.1 version.
```
└─┬ native-base@2.13.15
└── @codler/react-native-keyboard-aware-scroll-view@1.0.0
```
> resolving currentlyFocusedField Error

- src/basic/Tabs/ScrollableTabBar.js
The font size that was used previously was directly been taken from a variables files and we are required to have a font size coming directly from the parent, so just made the fix for that.
> FontSize fix for textHeading in scrollable tabs

- src/basic/Tabs/DefaultTabBar.js
- src/basic/Tabs/ScrollableTabBar.js
- src/basic/Tabs/index.js
@shivrajkumar this is a new PR based on your comment here: https://github.com/GeekyAnts/NativeBase/pull/3280#issuecomment-751583325
Using **NativeBase** with `react-native-web` latest version crashes the app because `ViewPropTypes` is undefined:
Related issues:
#3083
#3130
#3231
#3264
> ViewPropTypes error fix in src/basic/Tabs/

- src/basic/Accordion.js
- src/theme/variables/commonColor.js
- src/theme/variables/material.js
- src/theme/variables/platform.js
Reverts GeekyAnts/NativeBase#3240
> Revert "Feat/accordian disable row"

- src/components/primitives/Button/index.tsx
This PR fixes,
1. Modal CloseButton not responding on mouse click events 
- whitelist zIndex prop
2. Removes useButton from rn-aria as currently it's types only support Pressable component and it's not doing much here and made debugging complicated.
3. Fix - isDisabled not working on Buttons
4. Spacebar not registering click event on Button
> fix: v3 - isDisabled and modal close button not responding

- example/storybook/stories/components/composites/Snackbar/Hook.tsx
- src/components/composites/Snackbar/Snackbar.tsx
- src/components/composites/Toast/ToastItem.tsx
- src/components/composites/Toast/hooks.tsx
- src/components/composites/Toast/types.tsx
This PR adds accessibilityLiveRegion prop to Toast and Snackbar. [accessibilityLiveregion](https://reactnative.dev/docs/accessibility#accessibilityliveregion-android) works only on Android and Web. 
This isn't mentioned in the doc but [accessibilityAnnouncement](https://reactnative.dev/docs/accessibilityinfo#announceforaccessibility) is iOS only.
So, we can use accessibilityLiveRegion for android+web and accessibilityAnnouncement for iOS.
> v3 - Toast and snackbar accessibility live region

- example/package.json
- example/yarn.lock
- src/components/primitives/Link/index.tsx
- src/components/primitives/Link/useLink.ts
This PR increments rn-web version to 0.15 in example. 
RN web doesn't appear to have any significant breaking changes as [mentioned here](https://github.com/necolas/react-native-web/releases/tag/0.15.0)
This can be helpful for the breadcrumb fix which needed `<Text />` to support "target" prop before. 
In 0.15, View accepts hrefAttrs props as [mentioned here](https://github.com/necolas/react-native-web/releases/tag/0.15.0) so we can be consistent on all the platforms and use StyledLink (Box).
> fix - useLink to return hrefAttrs new prop in rn web 0.15

- src/core/Overlay/Wrapper.tsx
- src/core/Popover/Wrapper.tsx
This PR fixes
- Components not accessible via Talkback.
- Menu item is not clickable on Android.
> fix: menu clicks and talkback not focusing elements

- src/components/composites/Menu/MenuItem.tsx
- src/components/composites/Modal/Modal.tsx
- src/core/Overlay/Wrapper.tsx
- src/core/Overlay/types.ts
- src/core/Popover/Wrapper.tsx
- src/core/Popover/types.ts
- src/core/hybrid-overlay/HybridProvider.tsx
- src/hooks/index.ts
- src/hooks/useKeyboardDismissable.ts
This PR adds 
- keyboard dismissable behavior to Popover and sets default behavior to true for overlays and popovers.
- onAccessibilityEscape action in modal and overlays. This enables escape using Z gesture on iOS.
> v3 - Keyboard dismissable in popover and overlay

- src/utils/customProps/customExtra.ts
This PR removes pointer-events from styled system Props. This was leading to a crash on mobile if pointer-events is passed to Box.
> fix: v3 remove pointer events from styled system config

- package.json
- src/components/composites/FormControl/FormControl.tsx
- src/components/composites/FormControl/FormErrorMessage.tsx
- src/components/composites/FormControl/FormHelperText.tsx
- src/components/composites/FormControl/FormLabel.tsx
- src/components/composites/FormControl/index.tsx
- src/components/composites/FormControl/test/FormControl.test.tsx
- src/components/composites/FormControl/types.tsx
- src/components/composites/FormControl/useFormControl.tsx
- src/components/composites/NumberInput/NumberInput.tsx
- src/components/composites/NumberInput/NumberInputStepper.tsx
- src/components/composites/PinInput/PinInput.tsx
- src/components/primitives/Checkbox/Checkbox.tsx
- src/components/primitives/Checkbox/CheckboxGroup.tsx
- src/components/primitives/Input/index.tsx
- src/components/primitives/Input/types.ts
- src/components/primitives/Radio/RadioGroup.tsx
- src/components/primitives/Select/Select.tsx
- src/components/primitives/Slider/Slider.tsx
- src/core/NativeBaseProvider.tsx
- src/core/Overlay/Wrapper.tsx
- src/utils/accessibilityUtils.ts
- src/utils/index.ts
- src/utils/test-utils.tsx
- yarn.lock
This PR improves FormControl and Input accessibility. Tested on VoiceOver and added testcases for the same.
- `nativeID` passed to the form control will be passed to the form input directly. 
- `FormLabel` will have `htmlFor` that points to the `nativeID` of the form input.
- `FormErrorMessage` adds `aria-describedby` and `aria-invalid` pointing to
the form input.
- `FormHelperText` adds `aria-describedby` pointing to
the form input.
- `FormHelperText` adds/extends `aria-describedby` pointing to the form input.
> fix: v3 Form control accessibility

- src/components/composites/Tabs/TabBar.tsx
- src/components/composites/Tabs/TabViews.tsx
- src/components/composites/Tabs/Tabs.tsx
- src/components/composites/Tabs/types.tsx
This PR fixes Tabs not working in Prod build. 
Issue:
We were relying on type.name attribute to generate collection components for React Stately which doesn't work on prod build due to minification. 
Solution:
This PR adds displayName property to fix it.
This PR also adds keyboardActivation prop, which is used very commonly, we were already supporting it, just the prop was not being passed.
> fix: v3 tabs not working on prod build

- example/storybook/stories/components/primitives/Select/SelectLongList.tsx
- example/storybook/stories/components/primitives/Select/index.tsx
- src/components/composites/Actionsheet/Actionsheet.tsx
- src/components/composites/Actionsheet/ActionsheetContent.tsx
- src/components/primitives/Select/Select.tsx
- src/theme/components/actionsheet.ts
Fixes
- ActionSheet flickers when it's closed using a swipe gesture
- Select scroll behaviour when list of options is large
Features
- Added drag indicator line in ActionSheet. This is useful to indicate that the component is draggable.
- Added Select example with long list of options.
> fix: select scroll and actionsheet flicker on swipe

- example/storybook/stories/components/composites/Menu/Basic.tsx
- src/components/composites/Backdrop/index.tsx
- src/components/composites/Menu/Menu.tsx
- src/components/composites/Modal/Modal.tsx
- src/components/composites/Popover/Popover.tsx
- src/components/composites/Popper/Popper.tsx
- src/components/composites/Transitions/PresenceTransition.tsx
- src/components/composites/Transitions/Transition.tsx
- src/components/primitives/Button/Button.tsx
- src/components/primitives/Button/types.ts
- src/components/primitives/Overlay/ExitAnimationContext.ts
- src/components/primitives/Overlay/Overlay.tsx
- src/components/primitives/Overlay/index.ts
- src/components/primitives/Pressable/Pressable.tsx
- src/components/primitives/Pressable/types.ts
- src/theme/components/button.ts
On talkback, the accessibility focus should shift to the first element when opened
https://user-images.githubusercontent.com/23293248/123375758-f5334f00-d5a6-11eb-997c-10534de92c07.mp4
- Add _disable style prop in button
- Added a single Overlay Component which will handle back button behavior and accessibility on Android.
- This Overlay component can be used for Modal, Menu, Popover or Drawer (in future)
- Fix backdrop stays mounted when clicked multiple times before the entry animation is completed.
> Android accessibility fix and disabled style in button

- src/components/composites/Actionsheet/ActionSheetContext.ts
- src/components/composites/Actionsheet/Actionsheet.tsx
- src/components/composites/Actionsheet/ActionsheetContent.tsx
- src/components/composites/Actionsheet/types.tsx
- src/theme/components/actionsheet.ts
Fixes https://github.com/GeekyAnts/NativeBase/issues/3776
This PR adds `hideDragIndicator` and `_dragIndicator` props for hiding and styling ActionSheet's drag indicator
> Fix/3376 - Make drag indicator optional in actionsheet

- src/components/primitives/Checkbox/CheckboxGroup.tsx
This PR removes an additional wrapper which was added to Checkbox group for historical reasons.
> fix: remove checkbox group additional wrapper

- src/theme/components/input.ts
Fixes - https://github.com/GeekyAnts/NativeBase/issues/3783
In the current version, 
```
<Box px={2} p={4} />
```
Applied styles would be `paddingTop:4, paddingBottom:4, paddingLeft: 4, paddingRight: 4` 
In the new version, we're planning to make it such that more specific one wins so applied styles would be `paddingTop:4, paddingBottom:4, paddingLeft: 2, paddingRight: 2`. This is default behaviour in [react native and react native web](https://necolas.github.io/react-native-web/docs/styling/#how-it-works)
However, the above change is targeted in 3.1. In the meantime, this PR implements a patch to fix the issue for Input component.
> fix: 3783 input android padding top, bottom

- example/nativebase.config.ts
- src/core/NativeBaseContext.ts
- src/core/index.ts
- src/hooks/useContrastText.ts
Adds a feature to suppress accessible color warning https://github.com/GeekyAnts/NativeBase/issues/3785
```
<NativeBaseProvider config={{suppressColorAccessibilityWarning: true}}>
{App goes here}
</NativeBaseProvider>
```
> feat: add a flag to suppress accessibility color warning

- src/components/primitives/Link/index.tsx
Fixes https://github.com/GeekyAnts/NativeBase/issues/3851
Use _text from usePropResolution instead of incoming props.
Fixes _text not working in Link component's baseStyle/variants
> fix: link _text not working from theme

- example/storybook/stories/components/basic/KeyboardAvoidingView/Basic.tsx
Previously, isLargeScreen logic was applied to differentiate for web and mobile. But here, we don't want to show example on web platform. For that, using Platform property to detect the platform.
> fix: keyboardAvoidingView example will only run on mobile

- src/components/composites/Menu/types.ts
Error importing a module with the IPressableProps type
fixed an existing bug
> fix: import IPressableProps type

- src/components/composites/Avatar/Avatar.tsx
This PR fixes https://github.com/GeekyAnts/NativeBase/issues/3836 
- Passing null as child in Avatar was throwing error. 
- Added a check for null child.
> fix: avatar badge conditional rendering type of null issue

- example/storybook/stories/components/composites/Actionsheet/CustomBackdrop.tsx
- example/storybook/stories/components/composites/Actionsheet/index.tsx
- example/storybook/stories/components/composites/Modal/CustomBackdrop.tsx
- example/storybook/stories/components/composites/Modal/index.tsx
- src/components/composites/Actionsheet/types.tsx
- src/components/composites/Modal/Modal.tsx
- src/components/composites/Modal/types.ts
Fix for below Github Issue
[https://github.com/GeekyAnts/NativeBase/issues/3884](url)
Added _backdrop prop in actionsheet and modal to apply styles to backrop(overlay)
Added backdropVisible(same as overlayVisible) to maintain consistency in prop names
(overlayVisible still works)
Added Example with custom backdrop
> fix: actionsheet backdrop fix

- example/storybook/stories/components/composites/Fab/Kitchensink-Basic.tsx
- example/storybook/stories/components/composites/Fab/Kitchensink-Placement.tsx
- src/components/primitives/Radio/Radio.tsx
Radio in iOS and Android was passing size to Wrapper which was applied as height and width. This PR fixes the size issue.
> fix: radio size getting passed to wrapper

- src/core/color-mode/hooks.tsx
- src/core/color-mode/types.ts
- src/core/hybrid-overlay/HybridProvider.tsx
This PR fixes https://github.com/GeekyAnts/NativeBase/issues/3927
- There are 3 ways to set the color mode.
1. using [initialColorMode](https://docs.nativebase.io/color-mode#default-color-mode)
2. using [colorModeManager](https://docs.nativebase.io/color-mode#persisting-the-color-mode)
3. using [useSystemColorMode](https://docs.nativebase.io/color-mode#default-color-mode) - (This is added in this PR)
This is how the priority is defined.
- When `initialColorMode` and `useSystemColorMode` is passed => `useSystemColorMode` wins
- When `useSystemColorMode` and `colorModeManager` is passed => `colorModeManager` wins i.e. app will start with system color mode but value returned from colorModeManager.get will override it.
- When `initialColorMode` and `colorModeManager` is passed => …
> fix: use system color mode

- example/storybook/stories/components/primitives/Checkbox/FormControlled.tsx
- example/storybook/stories/components/primitives/Checkbox/checkboxGroup.tsx
- example/storybook/stories/components/primitives/Checkbox/controlledCheckbox.tsx
- example/storybook/stories/components/primitives/Checkbox/uncontrolledCheckbox.tsx
- example/storybook/stories/components/primitives/Radio/controlledRadio.tsx
- example/storybook/stories/components/primitives/Radio/customColor.tsx
- example/storybook/stories/components/primitives/Radio/customIcon.tsx
- example/storybook/stories/components/primitives/Radio/disabled.tsx
- example/storybook/stories/components/primitives/Radio/formControlled.tsx
- example/storybook/stories/components/primitives/Radio/invalid.tsx
- example/storybook/stories/components/primitives/Radio/playground.tsx
- example/storybook/stories/components/primitives/Radio/size.tsx
- example/storybook/stories/components/primitives/Radio/withRef.tsx
- src/components/primitives/Checkbox/Checkbox.tsx
- src/components/primitives/Checkbox/Checkbox.web.tsx
- src/components/primitives/Checkbox/CheckboxGroup.tsx
- src/components/primitives/Radio/Radio.tsx
This PR fixes the accessibility warnings described [here](https://github.com/GeekyAnts/NativeBase/issues/3947).
[General] [Fixed] - Radio and checkbox accessibility label warnings
Tested all the storybook examples of checkbox and radio on android, iOS and web
> fix: radio and checkbox accessibility warnings

- example/storybook/stories/components/composites/Menu/MenuPositions.tsx
- example/storybook/stories/components/composites/Popover/PopoverPositions.tsx
- example/storybook/stories/components/composites/Tooltip/TooltipPositions.tsx
The `Select` component has `accessibilityLabel` and `placeholder` props directly copied and pasted from the [Select component example.](https://github.com/GeekyAnts/NativeBase/blob/master/example/storybook/stories/components/primitives/Select/Basic.tsx) The props are unnecessary since the example is to demonstrate the Menu component, not the Select component. Also the content of the props are "out of place", since the example is not about selecting a programming language.
[General] [Removed] - Remove `accessibilityLabel` and `placeholder` props from `Select` component in Menu Example
It was directly tested from the snack player.
> fix: "out of place" props from Menu example

- src/components/primitives/Checkbox/Checkbox.tsx
- src/components/primitives/Checkbox/Checkbox.web.tsx
- src/components/primitives/Checkbox/SizedIcon.tsx
* Checkbox was using a similar component in both native and web platforms. Unified it under a single component.
* Replaced check icon with empty box of similar padding to make sure that the check mark was completely disappearing.
> fix: icon removed when no checked

- src/components/primitives/Radio/Radio.tsx
- src/components/primitives/Radio/Radio.web.tsx
- src/utils/index.ts
- src/utils/isEmptyObj.ts
Add an Error message prompting user to Add Radio.Group whenever Radio is used.
> Fix Radio error message when not in Group

- src/theme/tools/utils.ts
Fixes - cannot convert undefined or null in `hasValidBreakpoint` function
> fix: null check in hasValidBreakpoint

- src/components/primitives/Text/types.tsx
- src/theme/types.ts
Fixes - https://github.com/GeekyAnts/NativeBase/issues/4240 and https://github.com/GeekyAnts/NativeBase/issues/4239
Summary: Adds VariantType in Text and removes ts-ignore from AllProps
> fix: ts all props and text variant

- package.json
- yarn.lock
Upgrades react native aria overlays to 0.3.2 which fixes the interaction dependency occuring in https://github.com/GeekyAnts/NativeBase/issues/4011
> fix: update overlays dependency

- example/storybook/stories/components/composites/AspectRatio/Basic.tsx
- example/storybook/stories/components/composites/AspectRatio/EmbedImage.tsx
- example/storybook/stories/components/composites/AspectRatio/index.tsx
This PR fixes issue with docs build automation that is caused due to aspect ratio example.
> Fix: AspectRatio example breaking Docs build

- src/components/primitives/Select/Select.tsx
- src/components/primitives/Select/types.ts
This PR fixes and adds onOpen and onClose props for Select component, Requested in this issue: https://github.com/GeekyAnts/NativeBase/issues/4166
> Added onOpen and onClose props for Select

- src/components/composites/Toast/Toast.tsx
This is will allow users to set `Alert` props when calling `setToast` (access `testID` or layout props)
[General] [Fixed] - Spread Toast props to child Alert component
Works like before... the change is very light
> Spread Toast props to child Alert component

- src/components/composites/Toast/Toast.tsx
Info Icon and close button was going out of the screen for android and ios device when title of the info toast is long.
> fix: info toast long title

- src/components/primitives/Radio/Radio.tsx
- src/components/primitives/Radio/Radio.web.tsx
isDisabled as prop in FormControl was not disabling radio button
> fix: isDisabled disable radio in form control component

- src/theme/components/input.ts
input underlined variant was having wrong style.
https://github.com/GeekyAnts/NativeBase/issues/4517
> fix: input underlined variant

- src/components/primitives/Box/types.ts
Typing adjustment for custom themes
[General] [Fixed] - Typing color by custom themes
When creating a custom theme, the color token was not received by auto complete
> fix: typing color by custom themes

- src/components/primitives/Input/InputBase.tsx
The Input component rendered in Firefox is not perfect. The default outline of React Native `TextInput` was not hiding in Firefox browser.
> fix: firefox input component

- example/storybook/stories/components/primitives/Image/Sizes.tsx
- src/components/primitives/Image/index.tsx
Fix infinite loop in Image component
[This fix](https://github.com/GeekyAnts/NativeBase/pull/4529) is causing infinite loop in Image component when source is changed.
You can see the error in the example of `Image/FallbackSupport` in storybook.
I found this issue when I was using Modal to display Image in react native by passing source via props when it is opened.
this is the error
```
Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```
> fix: infinite loop in Image component

- src/theme/components/heading.ts
removed font family from base style for `Heading` component. It was injecting the wrong font family in some cases.  For Example for nested `Heading`, it was injecting the wrong font-family for inner `Heading`.
> fix: remove heading fontfamily

- src/components/composites/Toast/Toast.tsx
After calling `toast.show()` Toast provider overlaps screen elements and prevents onClick events to reach buttons etc. This was happening due to 100% width of `VStack` component in which `toasts` are added.
> fix: toast overlap issue

- src/components/primitives/Checkbox/Checkbox.tsx
- src/components/primitives/Checkbox/Checkbox.web.tsx
- src/components/primitives/Checkbox/CheckboxGroup.tsx
- src/components/primitives/Checkbox/types.tsx
- src/components/primitives/Radio/Radio.tsx
- src/components/primitives/Radio/Radio.web.tsx
- src/components/primitives/Radio/RadioGroup.tsx
- src/components/primitives/Radio/types.tsx
- src/theme/components/checkbox-group.ts
- src/theme/components/checkbox.ts
- src/theme/components/index.ts
- src/theme/components/radio-group.ts
- src/theme/components/radio.ts
- Completed theme decoupling for radio and checkbox component, added two new theme files for `RadioGroup` and `CheckboxGroup`.
- Added `_stack` prop in checkbox component
- This PR will also fix issue [#4670](https://github.com/GeekyAnts/NativeBase/issues/4670)
> fix: radio checkbox theme decoupling

- src/components/primitives/Select/Select.tsx
- src/components/primitives/Select/types.ts
- src/theme/components/select.ts
- Theme decoupling
- New pseudo prop  - `_actionSheetBody`
( props to be passed to underlying Flatlist in ActionSheet.Content. )
> fix: decoupling and added pseudo prop in select

- src/components/composites/Avatar/Avatar.tsx
Fixed fallback text issue for `undefined` and `null` source uri
> fix: avatar uri issue

- src/components/composites/FormControl/FormControlErrorMessage.tsx
Fixed`FormControl.ErrorMessage`  long error message overlap issue #4676
> fix: error message overlap

- src/theme/components/icon-button.ts
- fixed bg color on focus for dark mode
> fix: icon-button on focus bg color

- src/components/primitives/Input/types.ts
- Added `_stack` to the `IInputProps` for `input`
> fix: input _stack type issue

- src/hooks/useThemeProps/usePropsResolution.tsx
- Fixes the issue of `internal props` not getting applied.
- `_astrick` in `FormControl.Label`.
- `_icon` in `Alert`
- `_text` in `Menu.Item`.
> fix: internal pseudo prop

- src/components/composites/IconButton/index.tsx
`Icon` props not getting applied inside `IconButton`
- add `icon.props` while cloning the icon
> fix: add icon props in IconButton

- src/components/primitives/Input/types.ts
- RN TextInput doesn't have the same support as web Input for types hence we are removing the string typing from type prop for now.
> fix: remove string from input type

- src/components/composites/Transitions/Fade.tsx
- src/theme/components/transitions.ts
> fix: fade animation props

- src/components/composites/Transitions/Fade.tsx
- src/theme/components/transitions.ts
Reverts GeekyAnts/NativeBase#5004
> Revert "fix: fade animation props"

- src/components/primitives/Input/types.ts
This adds 'RefCallback' to ref property for primitive input in order to accommodate for libraries like react-hooks-form which pass a RefCallback type which is not currently accepted.
> Update types.ts for primitive Input

- .github/auto_assign.yml
- .github/stale.yml
- Extended number of days to 6 months for `stale-bot`.
- Replaced `PR` reviewer from `MD-Rehman` to `rayan1810` (Rohit) in `auto-assign-bot`.
> fix: extended time for stale bot and changed auto assign bot

- src/utils/getSpacedChildren.tsx
The way stack flattening is implemented right now leads to multiple children having the same key, resulting in these errors:
```
Encountered two children with the same key, .$.$.1
```
This PR fixes the issue by using the child's key or the index as prefix to generate unique keys.
Inspired from this repository: [grrowl/react-keyed-flatten-children](https://github.com/grrowl/react-keyed-flatten-children/blob/master/index.ts)
Linked issue: #4653 
fix: fixed same key for multiple children error due to stack flattening
> fix: fixed same key for multiple children error due to stack flattening

- src/components/composites/Popover/PopoverContent.tsx
`PopoverContent`  was breaking over the `falsy`, `null` or `string` value of children
> fix: popover break on falsy children value

- src/components/composites/Toast/Toast.tsx
- src/components/composites/Toast/types.ts
- fix: making toast keyboard inset optional with `avoidKeyboard` prop
> fix: making toast keyboard inset optional with avoidKeyboard prop

- src/components/primitives/Overlay/Overlay.tsx
When the modal and the overlay component were shown, the background did not cover the status bar. Suppose the status bar color is white. It looks a little ugly.
[General] [Fixed] - Fix android overlay component does not cover statusbar
> fix | android overlay component does not cover statusbar

- example/storybook/stories/components/primitives/Checkbox/FormControlled.tsx
- Icon is not aligned with the text.(SB checkBox Formcontrol)
> fix: icon is not aligned with the text

- src/components/primitives/Input/Input.tsx
- src/components/primitives/Input/types.ts
- src/theme/components/input.ts
- src/utils/index.ts
- src/utils/resolveStackStyleInput.ts
- `focusOutlineColor` and `invalidOutlineColor` will now change borders and outlineColor when isFocused and isInvalid is true respectively. #3856
> fix: input outline color props

- src/components/composites/index.ts
- src/components/primitives/Pressable/index.tsx
- src/components/primitives/Radio/index.tsx
- src/components/primitives/index.ts
- src/hooks/index.ts
- src/index.tsx
- src/utils/index.ts
We're considering implement Radio variants but there're some hooks & context wasn't disposed. So I created this PR to export them out. If there's any problem, please let me know and fix it timely. Thank you very much!
I has export `useHasResponsiveProps` in `hooks` and `wrapStringChild`, `RadioContext` and some necessary type, hooks and context that make the re-implementation easier.
> feat: expose the internal hooks and context for Radio variant

- src/components/composites/Fab/types.tsx
Old Content - 
Placement of the Fab
Text to be displayed in Fab
Icon to be displayed in Fab
Refer this solution before using this prop
New Content - 
Placement of the Fab.
Text to be displayed in Fab.
Icon to be displayed in Fab.
Refer to this solution before using this prop-
> fix: content changes in fab types

- src/components/composites/Transitions/types.tsx
Old Content - 
Callback invoked when transition is completed
Styles before the transition starts
Entry animation styles
Exit animation styles
Determines whether to start the animation
Defaults to `View`
New Content - 
Callback invoked when the transition is completed.
Styles before the transition starts.
Entry animation styles.
Exit animation styles.
Determines whether to start the animation.
Defaults to `View`.
> fix: content changes in transitions types

- src/components/primitives/Image/types.ts
Old Content - 
The alt text that describes the image. This will be added as accessibilityLabel in android/iOS and alt on web
In event there was an error loading the src, specify a fallback source.
Opt out of the fallbackSource logic and show alternative text
In event there was an error loading the src, specify a fallback JSX Element.
New content - 
The alt text that describes the image. This will be added as accessibilityLabel in android/iOS and alt on web.
In the event of an error loading the src, specify a fallback source.
Opt out of the fallbackSource logic and show alternative text.
In the event of an error loading the src, specify a fallback JSX Element.
> fix: content changes in image types

- src/components/composites/Avatar/types.tsx
Old Content - 
The size of the avatar
For providing props to Image component inside Avatar.
ref to be attached to Avatar wrapper
New Content - 
The size of the avatar.
For providing props to Image component inside the Avatar.
ref to be attached to the Avatar wrapper.
> fix: content changes in avatar-types

- src/components/composites/Popover/types.ts
**Old Content -**
If true, the popover will be opened by default
Useful for conrolling the open state
This element will be used as a Trigger for the popover
content should overlap with the trigger
Popover children
If true, the modal will close when Escape key is pressed
This function will be invoked when popover is opened
If true, the popover will be opened by default.
Useful for controlling the open state.
This element will be used as a Trigger for the popover.
content should overlap with the trigger.
Popover children.
If true, the modal will close when Escape key is pressed.
This function will be invoked when popover is opened.
> fix: content changes in popover types

- src/components/composites/Menu/types.ts
- src/components/composites/Modal/types.ts
**Old Content -** 
Useful for controllable state behaviour
Callback invoked when the modal is closed
If true, the modal will be opened by default
The size of the modal
If true, the modal will close when the overlay is clicked
If true, the modal will close when Escape key is pressed
If true, a backdrop element is visible
Sets the animation type
Useful for controllable state behavior. 
Callback invoked when the modal is closed.
If true, the modal will be opened by default.
The size of the modal.
If true, the modal will close when the overlay is clicked.
If true, the modal will close when Escape key is pressed.
If true, a backdrop element is visible.
Sets the animation type.
> Fix:  content changes in modal types

- src/components/composites/Menu/types.ts
**Old Content -** 
It'll also be called when user attempts to close the menu via Escape key or backdrop press.
This element will be used as a Trigger for the menu
This function will be invoked when menu is opened
Whether menu should be closed when a menu item is pressed
If true, the menu will be opened by default
Useful for conrolling the open state
menu content should overlap with the trigger
Children of Menu Item
Whether menu item is disabled
Props to be passed to Text
typeahead menu feature
The title of the menu group
The children of Menu group
The initial value of the option group
The value of the option group
Function called when selection changes
It will also be called when the user attempts to close the menu via Escape key or backdrop press.
This element will be …
> fix: content changes in menu types

- src/components/primitives/Text/types.tsx
**Old Content -**
Make the text bold.
If true, it'll render an ellipsis when the text exceeds the width of the viewport or maxWidth set.
Make the text italic.
Underline the text.
A horizontal line through its center.
Highlight the text with a yellow background.
Used to make the text bold.
If true, it will render an ellipsis when the text exceeds the width of the viewport or maxWidth set.
Used to make the text italic.
A horizontal line through the center of the text.
> fix: content changes in text types

- src/components/composites/Skeleton/types.tsx
**Old Content -** 
If true, it'll render its children
No of Lines in text
If true, it will render its children
Number of Lines in text
> fix: content changes in skeleton types

- src/components/primitives/Input/types.ts
**Old Content -**
This prop allow you to change outlineColor when input is in focused state
This prop allow you to change outlineColor when input is in invalid state
This prop allows you to change outlineColor when input is in the focused state
This prop allows you to change outlineColor when input is in invalid state
> fix: content changes in input types

- src/components/primitives/Checkbox/Checkbox.tsx
When extract _accessibilityProps_ from _nonLayoutProps_  we missing _accessibilityLabel_ key; so that lead to inconsistent accessibility announcement between **Radio** and **Checkbox**
Ex: with accessibilityLabel="This is example label"
Then accessibility announcement on components will be :
- Radio:  not checked, This is example label, Radio button.
- Checkbox: not checked, Checkbox, This is example label.
[General] - [Fixed] - fix checkbox a11y announcement inconsistent with Radio component
It is not a breaking change.
> extract accessibilityLabel from nonLayoutProps

- src/components/composites/IconButton/index.tsx
`<IconButton>` isDisabled is not working properly.
Try working with Snack.
https://snack.expo.dev/@suzu_prog/nbiconbutton-isdisabled-bug
`<IconButton>` has `isDisabled`, but onPress works.
`<Button>` has `isDisabled` working fine.
Therefore, onPress does not work.
[General] [Fixed] - Fix icon button isDisabled prop
https://user-images.githubusercontent.com/60243840/192835079-01155e6c-488e-4a3f-b79a-7a299bce7a33.mov
> fix: icon button `isDisabled` prop

- example/storybook/stories/components/primitives/Icon/CreateIcon.tsx
Since NativeBase already has a Circle component, it conflicts with the react native svg Circle component. hence naming it CircleSvg for the docs to showcase the example properly.
> fix: update create icon example to fix docs

- src/core/color-mode/hooks.tsx
`removeEventListener` is deprecated for a several years https://reactnative.dev/docs/0.65/appstate#removeeventlistener
[General] [Fix] - Warning on react-native 0.65+
> fix: warning on RN v0.65+

- example/storybook/stories/components/primitives/Input/Addons.tsx
Fix: Addons example in input component placed in the center.
> fix: addons example in  input component

- src/components/primitives/Checkbox/Checkbox.tsx
NativeBase allow user to pass accessbilityHint for checkbox (ICheckboxProps) but accessibilityHint prop is not being extracted. Currently Hint is not being announce and this PR resolves that bug.
> fix(checkbox):passing accessibilityHint prop to the component

- src/components/primitives/Box/types.ts
LinearGradient `locations` props was wrongly typed. In js code it was working fine.
(this is reopening of https://github.com/GeekyAnts/NativeBase/pull/5025 which was closed by mistake)
[General] [Fixed] - Linear gradient `locations` TypeScript typing
This should work in tsx
```
<Box
bg={{
linearGradient: {
colors: ["coral", "#2D3D4DFF"],
locations: [0.9, 1],
},
}}>
```
> fix: linear gradient locations typing

- .github/workflows/build.yml
- README.md
- package.json
- sonar-project.properties
- src/core/color-mode/hooks.tsx
- yarn.lock
migrates to use-sync-external-store to support react 18 and nextjs
React 18.x and nextjs 13.x raises the error 
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
Applying the same upgrade that nextjs applied to native-base fixes the error
https://github.com/vercel/next.js/pull/36733/files
[refactor] [Changed] - Migrate to use-sync-external-store from use-subscription
Upgrading a project to react 18 and nextjs 13 resolves the error
> refactor: replaces use-subscription with use-sync-external-store
